const sliderImg2 = [
    {
        src: 'https://us.louisvuitton.com/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-flowers.png?imwidth=216%20216w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-flowers.png?imwidth=320%20320w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-flowers.png?imwidth=456%20456w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-flowers.png?imwidth=656%20656w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-flowers.png?imwidth=824%20824w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-flowers.png?imwidth=1080%201080w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-flowers.png?imwidth=1240%201240w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-flowers.png?imwidth=2048%202048w',
        alt: 'img-1',
    },
    {
        src: 'https://us.louisvuitton.com/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-faces.png?imwidth=216%20216w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-faces.png?imwidth=320%20320w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-faces.png?imwidth=456%20456w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-faces.png?imwidth=656%20656w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-faces.png?imwidth=824%20824w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-faces.png?imwidth=1080%201080w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-faces.png?imwidth=1240%201240w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-faces.png?imwidth=2048%202048w',
        alt: 'img2',
    },
    {
        src: 'https://us.louisvuitton.com/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-infinity.png?imwidth=216%20216w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-infinity.png?imwidth=320%20320w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-infinity.png?imwidth=456%20456w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-infinity.png?imwidth=656%20656w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-infinity.png?imwidth=824%20824w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-infinity.png?imwidth=1080%201080w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-infinity.png?imwidth=1240%201240w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-infinity.png?imwidth=2048%202048w',
        alt: 'img3',
    },
    {
        src: 'https://us.louisvuitton.com/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-pumpkins.png?imwidth=216%20216w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-pumpkins.png?imwidth=320%20320w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-pumpkins.png?imwidth=456%20456w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-pumpkins.png?imwidth=656%20656w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-pumpkins.png?imwidth=824%20824w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-pumpkins.png?imwidth=1080%201080w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-pumpkins.png?imwidth=1240%201240w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/legendary-pumpkins.png?imwidth=2048%202048w',
        alt: 'img4',
    },
];

export default sliderImg2;
