const products = [
    {
        id: 'QBB205',
        name: 'Tambour Street Diver Chronograph',
        price: '$11,105.00',
        detail: 'Automatic movement, visible through the sapphire caseback',
        intro: "The Tambour Street Diver Chronograph enriches the Street Diver range with an essential complication. The chronograph function underscores the Maison's pursuit of practicality and readability in this sporty collection, and revisists the aesthetic codes of the 2021 GPHG award-winning design. The Street Diver Skyline Blue Chronograph features a perfectly-proportioned Tambour case, contrasting finishes and luminescent indexes, for a precision timepiece that will add a sporty, nautical-chic allure to any silhouette.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver-chronograph--QBB205_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver-chronograph-collections--QBB205_PM1_Interior%20view.png?wid=824&hei=824',
    },
    {
        id: 'QBB204',
        name: 'Tambour Street Diver Chronograph',
        price: '$11,105.00',
        detail: 'Automatic movement, visible through the sapphire caseback',
        intro: "The Tambour Street Diver Chronograph enriches the Street Diver range with an essential complication. The chronograph function underscores the Maison's pursuit of practicality and readability in the collection, lending these models an even bolder spirit. The Street Diver Neon Black Chronograph features a perfectly-proportioned Tambour case, contrasting finishes and luminescent indexes, for a precision timepiece that will add a sporty, daring allure to any silhouette.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver-chronograph--QBB204_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver-chronograph-collections--QBB204_PM1_Back%20view.png?wid=824&hei=824',
    },
    {
        id: 'QBB172',
        name: 'Tambour Street Diver',
        price: '$7,805.00',
        detail: 'Automatic movement',
        intro: 'Boasting an uncompromisingly modern look, the Tambour Street Diver combines traditional diving features with unexpected design in one versatile creation. The Skyline Blue model combines navy and light blue tones on a sunray dial, with a rubber strap that echoes the effect. Robust and edgy, it will bring a casual touch to any outfit.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver--QBB172_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver-collections--QBB172_PM1_Interior%20view.png?wid=824&hei=824',
    },
    {
        id: 'QBB173',
        name: 'Tambour Street Diver',
        price: '$7,805.00',
        detail: 'Automatic movement',
        intro: "Robust and edgy, the Tambour Street Diver is the House's sportiest yet most versatile watchmaking creation. The Neon Black model showcases a modern style that is high in contrast, with black and fluo yellow tones complementing one another on the dial, case and strap. Combining traditional diving features with colorful, creative and unconventional design, it is pure Louis Vuitton.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver--QBB173_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver-collections--QBB173_PM1_Interior%20view.png?wid=824&hei=824',
    },
    {
        id: 'QBB196',
        name: 'Tambour Damier Chronograph',
        price: '$7,905.00',
        detail: 'Polished stainless steel case with over-moulded navy rubber crown',
        intro: "Inspired by the House's Damier canvas, the Tambour Damier Chronograph offers a new take on the classic Tambour design. The iconic canvas is reproduced on the watch’s dial, alongside a V signature that extends onto the flange. This steel version features contrasting red and white for a sporty look, alongside a rubber strap with protruding Louis Vuitton lettering.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-damier-chronograph--QBB196_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-damier-chronograph-collections--QBB196_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB175',
        name: 'Tambour Street Diver',
        price: '$5,805.00',
        detail: 'High precision quartz movement',
        intro: 'This Pacific White model brings a feminine touch to the versatile Tambour Street Diver range. Casual and sporty, it combines traditional dive watch functions with the colorful, creative and unconventional style unique to Louis Vuitton. Its bright colors, contrasting finished and luminescent indexes will add a modern twist to any outfit.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver--QBB175_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver-collections--QBB175_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB174',
        name: 'Tambour Street Diver',
        price: '$16,900.00',
        detail: 'Automatic movement',
        intro: 'The Black Blaze model brings a sophisticated touch to the Tambour Street Diver range. Polished pink gold contrasts with a sporty feel, creating an uncompromisingly modern effect. A versatile new take on the iconic Tambour silhouette, it combines traditional diving watch features with creative and unexpected design.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver--QBB174_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver-collections--QBB174_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB195',
        name: 'Tambour Outdoor Chronograph',
        price: '$6,110.00',
        detail: 'High-precision quartz movement',
        intro: "The Tambour Outdoor Chronograph embodies the House's art of travel in a sporty, modern spirit. The Urban Jungle model is the ideal exploration tool, with GMT and chronograph functions united in a luxury watch with on-trend city style. The sandblasted green dial displays two-tone counters and bright colour accents for optimal readability. A signature rubber strap completes the piece.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-outdoor-chronograph--QBB195_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-outdoor-chronograph-collections--QBB195_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB161',
        name: 'Tambour Damier Graphite Race',
        price: '$5,755.00',
        detail: 'Automatic movement with 50-hour power reserve',
        intro: "Perfect for casual and sporty looks, this new version of Louis Vuitton's emblematic Tambour watch is inspired by the House's iconic Damier Graphite canvas. Like a hallmark, the Gaston-Louis Vuitton's V signature enlightens the entire dial, adding a modern twist. Bold and fresh, this version echoes Virgil Abloh's collections, with an eye-catching contrast between black, silver and green.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-damier-graphite-race--QBB161_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-damier-graphite-race-collections--QBB161_PM1_Other%20view5.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB160',
        name: 'Tambour Damier Graphite Race Chronograph',
        price: '$8,355.00',
        detail: 'Automatic movement with 42-hour power reserve',
        intro: "Perfect for casual and sporty looks, this new version of Louis Vuitton's emblematic Tambour watch is inspired by the House's iconic Damier Graphite canvas. Like a hallmark, the Gaston-Louis Vuitton's V signature enlightens the entire dial, adding a modern twist. Bold and fresh, this chronograph version echoes Virgil Abloh's collections, with an eye-catching contrast between black, silver and green.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-damier-graphite-race-chronograph--QBB160_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-damier-graphite-race-chronograph-collections--QBB160_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB198',
        name: 'Tambour Street Diver',
        price: '$10,505.00',
        detail: 'High precision quartz movement',
        intro: 'The Gold Lagoon edition of the Tambour Street Diver watch brings the precious touch of 18-karat pink gold to this sporty, feminine dive watch. The glossy white-lacquered dial features luminescent indexes and golden polished hands. Set on a modern white rubber strap, this casual yet sophisticated piece is the ideal complement to any off-duty outfit.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver--QBB198_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-street-diver-collections--QBB198_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB171',
        name: 'Tambour Slim Monogram 39MM',
        price: '$3,820.00',
        detail: 'High-precision quartz movement',
        intro: 'The Tambour Slim collection features a thin watch signed with the iconic Louis Vuitton Monogram pattern highlighted by delicate diamond indexes. Symbol of elegance, this black variation is a must have in every women wardrobe and will prove its versatility as any black dress, timeless and distinctive.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-39mm--QBB171_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-39mm-collections--QBB171_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB170',
        name: 'Tambour Slim Monogram 33MM',
        price: '$3,570.00',
        detail: 'High-precision quartz movement',
        intro: 'The Tambour Slim collection features a thin watch signed with the iconic Louis Vuitton Monogram pattern highlighted by delicate diamond indexes. Symbol of elegance, this black variation is a must have in every women wardrobe and will prove its versatility as any black dress, timeless and distinctive.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-33mm--QBB170_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-33mm-collections--QBB170_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB169',
        name: 'Tambour Slim Monogram 28MM',
        price: '$2,930.00',
        detail: 'High-precision quartz movement',
        intro: 'The Tambour Slim collection features a thin watch signed with the iconic Louis Vuitton Monogram pattern highlighted by delicate diamond indexes. Symbol of elegance, this black variation is a must have in every women wardrobe and will prove its versatility as any black dress, timeless and distinctive.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-28mm--QBB169_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-28mm-collections--QBB169_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBBB57',
        name: 'Tambour Slim Monogram 39.5',
        price: '$3,705.00',
        detail: 'High-precision quartz movement',
        intro: 'The Tambour Slim collection features a thin watch signed with the iconic Louis Vuitton Monogram pattern. The watch is worn with an interchangeable strap equipped with Louis Vuitton patented system.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-39-5--QBBB57_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-39-5-collections--QBBB57_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBBB56',
        name: 'Tambour Slim Monogram 33',
        price: '$3,505.00',
        detail: 'High-precision quartz movement',
        intro: 'The Tambour Slim collection features a thin watch signed with the iconic Louis Vuitton Monogram pattern. The watch is worn with an interchangeable strap equipped with Louis Vuitton patented system.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-33--QBBB56_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-33-collections--QBBB56_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBBB55',
        name: 'Tambour Slim Monogram 28 ',
        price: '$3,295.00',
        detail: 'High-precision quartz movement',
        intro: 'The Tambour Slim collection features a thin watch signed with the iconic Louis Vuitton Monogram pattern. The watch is worn with an interchangeable strap equipped with Louis Vuitton patented system.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-28--QBBB55_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-slim-monogram-28-collections--QBBB55_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBBB97',
        name: 'Tambour Monogram 39.5mm',
        price: '$3,705.00',
        detail: 'High-precision quartz movement',
        intro: 'The Tambour watch, unique and recognizable, pays tribute to the first musical instrument whose rhythm is reminiscent of passing time. As a result of a clever alliance between two icons, the Tambour case and the Monogram canvas of the leather goods, the Tambour Monogram stands out as the emblematic feminine watch of Louis Vuitton.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-39-5mm--QBBB97_PM1_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-39-5mm-collections--QBBB97_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBBB96',
        name: 'Tambour Monogram 34mm',
        price: '$3,505.00',
        detail: 'Interchangeable Monogram canvas strap equipped with Louis Vuitton patented system',
        intro: 'The Tambour watch, unique and recognizable, pays tribute to the first musical instrument whose rhythm is reminiscent of passing time. As a result of a clever alliance between two icons, the Tambour case and the Monogram canvas of the leather goods, the Tambour Monogram stands out as the emblematic feminine watch of Louis Vuitton.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-34mm--QBBB96_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-34mm-collections--QBBB96_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBBB95',
        name: 'Tambour Monogram 28mm',
        price: '$3,295.00',
        detail: 'High-precision quartz movement',
        intro: 'The Tambour watch, unique and recognizable, pays tribute to the first musical instrument whose rhythm is reminiscent of passing time. As a result of a clever alliance between two icons, the Tambour case and the Monogram canvas of the leather goods, the Tambour Monogram stands out as the emblematic feminine watch of Louis Vuitton.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-28mm--QBBB95_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-28mm-collections--QBBB95_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB165',
        name: 'Tambour Monogram 28MM',
        price: '$5,755.00',
        detail: 'High-precision quartz movement',
        intro: "As the Louis Vuitton's emblematic timepiece, the Tambour watch represents a clever combination of subtle elegance and strong personality. Entirely developed in our manufacture La Fabrique du Temps in Geneva, its dial faithfully reproduces the iconic Monogram canvas and showcase the House’s signature look. This versatile and timeless watch mixes brown and gold in a perfect combination to enlight a feminine look.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-28mm--QBB165_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-28mm-collections--QBB165_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB166',
        name: 'Tambour Monogram 34MM',
        price: '$6,155.00',
        detail: 'High-precision quartz movement',
        intro: "As the Louis Vuitton's emblematic timepiece, the Tambour watch represents a clever combination of subtle elegance and strong personality. Entirely developed in our manufacture La Fabrique du Temps in Geneva, its dial faithfully reproduces the iconic Monogram canvas and showcase the House’s signature look. This versatile and timeless watch mixes brown and gold in a perfect combination to enlight a feminine look.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-34mm--QBB166_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-monogram-34mm-collections--QBB166_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB129',
        name: 'Tambour Moon Dual Time 39.5mm',
        price: '$4,420.00',
        detail: 'High-precision quartz movement',
        intro: 'Feminine and sophisticated, the Tambour Moon Dual Time Black & White provides a contemporary expression of the art of travel. Thanks to a 24-hour display, both local and home times are clearly readable on its attractive concave dial, whose printed Monogram flowers combine with a flower-shaped GMT hand to evoke Louis Vuitton’s heritage. The dial’s concave design and its sunray-brushed surface create delicate plays of light.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-dual-time-39-5mm--QBB129_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-dual-time-39-5mm-collections--QBB129_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB128',
        name: 'Tambour Moon Dual Time 35mm',
        price: '$8,820.00',
        detail: 'High-precision quartz movement',
        intro: 'Feminine and sophisticated, the Tambour Moon Dual Time Black & White provides a contemporary expression of the art of travel. Thanks to a 24-hour display, both local and home times are clearly readable on its attractive concave dial, whose printed Monogram flowers combine with a flower-shaped GMT hand to evoke Louis Vuitton’s heritage. The dial’s concave design and its sunray-brushed surface create delicate plays of light. This 35mm version also includes diamond-set lugs for added luxury.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-dual-time-35mm--QBB128_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-dual-time-35mm-collections--QBB128_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB126',
        name: 'Tambour Moon Dual Time 35mm',
        price: '$4,220.00',
        detail: 'High-precision quartz movement',
        intro: 'Feminine and sophisticated, the Tambour Moon Dual Time Black & White provides a contemporary expression of the art of travel. Thanks to a 24-hour display, both local and home times are clearly readable on its attractive concave dial, whose printed Monogram flowers combine with a flower-shaped GMT hand to evoke Louis Vuitton’s heritage. The dial’s concave design and its sunray-brushed surface create delicate plays of light.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-dual-time-35mm--QBB126_PM1_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-dual-time-35mm-collections--QBB126_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB152',
        name: 'Tambour Moon Divine 35MM',
        price: '$6,955.00',
        detail: 'High-precision quartz movement',
        intro: 'Glamourous and elegant, the Tambour Moon Divine collection features sophisticated reinterpretation of the Monogram flowers, paved with diamonds. The stainless steel case displays a unique inward curve, giving the watch a crescent-shaped profile. This 35mm model in black lacquer and diamonds offers a dressy, feminine and joyfull look to refined women. The watch is worn with an interchangeable strap equipped with Louis Vuitton patented system. Black Alligator or Monogram vernis straps are recommended to match perfectly with the dial design.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-divine-35mm--QBB152_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-divine-35mm-collections--QBB152_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB154',
        name: 'Tambour Moon Divine 39,5MM',
        price: '$9,205.00',
        detail: 'High-precision quartz movement',
        intro: 'Glamourous and elegant, the Tambour Moon Divine collection features sophisticated reinterpretation of the Monogram flowers, paved with diamonds. The stainless steel case displays a unique inward curve, giving the watch a crescent-shaped profile. This 39.5mm model in white mother-of-pearl and diamonds offers a dressy, feminine and joyfull look to refined women. The watch is worn with an interchangeable strap equipped with Louis Vuitton patented system. White Alligator or Monogram vernis straps are recommended to match perfectly with the dial design.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-divine-39-5mm--QBB154_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-divine-39-5mm-collections--QBB154_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'QBB151',
        name: 'Tambour Moon Divine 28MM',
        price: '$5,955.00',
        detail: 'Tambour Moon stainless steel case',
        intro: 'Glamourous and elegant, the Tambour Moon Divine collection features sophisticated reinterpretation of the Monogram flowers, paved with diamonds. The stainless steel case displays a unique inward curve, giving the watch a crescent-shaped profile. This 28mm model in black lacquer and diamonds offers a dressy, feminine and joyfull look to refined women. The watch is worn with an interchangeable strap equipped with Louis Vuitton patented system. Black Alligator or Monogram vernis straps are recommended to match perfectly with the dial design.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-divine-28mm--QBB151_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-tambour-moon-divine-28mm-collections--QBB151_PM1_Side%20view.png?wid=1240&hei=1240',
    },
];

export default products;
