const products = [
    {
        id: 'GI0597',
        name: 'Porcelain Vase Noé BB',
        price: '$2,390.00',
        detail: '9.4 x 9.1 x 5.9 inches/24 x 23 x 15 cm White',
        intro: 'In a stunning display of House craftsmanship, this porcelain vase is rendered to the exact dimensions of the Noé BB handbag. Its hard, polished surface convincingly captures the soft folds of leather and canvas. Adding further likeness, the piece is embossed with an allover Monogram pattern.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-porcelain-vase-no%C3%A9-bb--GI0597_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-porcelain-vase-no%C3%A9-bb-monogram-highlights--GI0597_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R96612',
        name: 'Belt Lounge Chair By Atelier Oï',
        price: '$32,500.00',
        detail: '58 x 33.2 x 24.9 inches (length x Height x Width)',
        intro: "Elegantly beautiful and extremely comfortable, Atelier Oï's Belt Lounge Chair features 14 broads, precision-cut strips of rich Louis Vuitton leather stretched across a graceful metal and wood frame. The straps - which are available in different colours - are held in place by heavyweight gilded buckles and solid studs in the back to create a smoothly undulating dune-like surface. Each Belt Lounge Chair is a statement to Atelier Oï's distinctive design vision and Louis Vuitton's long-standing leatherworking savoir-faire.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-belt-lounge-chair-by-atelier-o%C3%AF--R96612_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-belt-lounge-chair-by-atelier-o%C3%AF-home--R96612_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M20292',
        name: 'Coffret Trésor 24',
        price: '$5,300.00',
        detail: '9.4 x 5.1 x 6.7 inches (length x Height x Width)',
        intro: 'The medium-size treasure case combines the simplicity of Monogram canvas with the originality of a brightly coloured lining. It securely holds letters, jewellery or other small treasures.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tr%C3%A9sor-24--M20292_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tr%C3%A9sor-24-monogram-canvas-travel--M20292_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R08760',
        name: 'Los Angeles City Guide, English Version',
        price: '$43.00',
        detail: '5.4 x 8.3 inches',
        intro: "Since 1998, Louis Vuitton City Guides have established themselves as the ultimate travel companions, bringing to life the world's most fascinating cities for business and leisure travelers alike. To capture the spirit of each city, Louis Vuitton reaches out to journalists, writers and major figures in the world of art and letters, whose contributions - together with those of artists, businesspeople and creative talents from many fields - make each City Guide a publication like no other. From five-star hotels to boutique concepts, gourmet restaurants to neighborhood bistros, antique shops to designer hubs, museums and monuments, each Louis Vuitton City Guide is a treasure trove of invaluable information, which reveals the pleasures each city has to offer. Every City Guide also features a special guest contributor, who takes the reader on a personal exploration of their home city, along the way sharing tips on their favorite spots. Last but not least, exclusive, previously unpublished photography by the Tendance Floue collective offers a fresh look at each destination.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-los-angeles-city-guide-english-version--R08760_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-los-angeles-city-guide-english-version-books-and-stationery--R08760_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M10097',
        name: 'Malle Cocktail',
        price: '$148,000.00',
        detail: '22 x 51.2 x 17.7 inches (length x Height x Width)',
        intro: 'The historical Cocktail Trunk is reinvented in Monogram Eclipse. An exceptional Cocktail Trunk celebrating New York festive spirit in the purest tradition of barmen. Magnifying the House historical know-how, this spectacular trunk adorns a beautiful blue microfiber lining, bringing to light the pureness of its crystal service.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-malle-cocktail--M10097_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-malle-cocktail-monogram-eclipse-canvas-trunks-and-travel--M10097_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R96715',
        name: 'Signature Armchair Outdoor By Frank Chou',
        price: '$42,000.00',
        detail: 'Green Turquoise',
        intro: "With their flowing and delicate silhouette, the graceful arches of Frank Chou's Signature Armchair and Sofa recall elegant calligraphy brushstrokes and were inspired by terraced fields in Yunnan, China, and the naturally sculpted forms of Antelope Canyon, Arizona, USA. This first Objet Nomade specifically designed for exterior use is upholstered with “Brio”, an innovative, colorful designed fabric from renowned Italian brand PAOLA LENTI. The Signature Sofa & Armchair are available in multiple color combinations and comfortably proportioned. The sofa’s three-meter length easily seats four people and is accompanied by the Signature Armchairs to form a complete seating set.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-signature-armchair-outdoor-by-frank-chou--R96715_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-signature-armchair-outdoor-by-frank-chou-home--R96715_PM1_Ambiance%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0822',
        name: 'Monogram Flower Trinket Bowl',
        price: '$885.00',
        detail: '10.2 x 3.3 x 10.2 inches (length x Height x Width)',
        intro: 'This Monogram Flower Trinket bowl displays an elegant profile while offering handy storage space. This sleek box features a striking petal-shaped exterior and plush microfiber lining for an opulent finish. With its bold hue, luxurious wood, and leather construction, it will instantly elevate home and office interiors.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-flower-trinket-bowl--GI0822_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-flower-trinket-bowl-s00-holiday-gifts-for-him--GI0822_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0772',
        name: 'Flask Holder Monogram Velvet',
        price: '$2,170.00',
        detail: '2.8 x 9.1 x 2.8 inches (length x Height x Width)',
        intro: 'This ultra-stylish and transportable Monogram Velvet flask holder is a lively addition to the Pre-Fall 2022 Sport Collection. The plush material gives this eye-catching vessel a texture that looks as good as it feels. Elevated by a sleek leather strap and Louis Vuitton signature name tag, it is a functional piece for on and off the court.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-flask-holder-monogram-velvet--GI0772_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-flask-holder-monogram-velvet-monogram-velours-sports-and-lifestyle--GI0772_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0884',
        name: 'Skateboard Mng Comics',
        price: '$2,580.00',
        detail: '80cm x 21cm x 10cm',
        intro: "Inspired by the comic-book theme of the Spring-Summer 2023 men's show, the Monogram Comics skateboard is a collector's item for fashion lovers and skate enthusiasts alike. Its maple-wood deck features the colorful Monogram Comics print on one side and a cartoon-style Louis Vuitton signature on the other. In a further fun detail, each wheel is printed with the House signature and a different pair of cartoon eyes.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-skateboard-mng-comics--GI0884_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-skateboard-mng-comics-s00-sports-and-lifestyle--GI0884_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0881',
        name: 'Rainbow Rug',
        price: '$5,550.00',
        detail: '63 x 0.6 x 37.4 inches (length x Height x Width)',
        intro: "The LV Rainbow rug is an exceptional design inspired by the LV Rainbow patch seen on key pieces at Louis Vuitton's Spring-Summer 2023 men's fashion show. Entirely hand-woven from pure wool, its bright colors and original shape will make a statement wherever it is placed, creating a warm and welcoming ambiance.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-rainbow-rug--GI0881_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-rainbow-rug-s00-home-textile--GI0881_PM1_Ambiance%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M10130',
        name: 'Coffret Trésor 24',
        price: '$5,300.00',
        detail: '9.4 x 5.1 x 6.7 inches (length x Height x Width)',
        intro: 'Like a rainbow, the Coffret Trésor is reinterpreted with colorful Bleu Lagon lining, that will please any Hardsided collector.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tr%C3%A9sor-24--M10130_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tr%C3%A9sor-24-monogram-trunks-and-travel--M10130_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R09018',
        name: 'Louis Vuitton Virgil Abloh, English Version',
        price: '$140.00',
        detail: 'Text by Anders Christian Madsen',
        intro: 'The first book on the visionary designer since his passing on November 28, 2021, Louis Vuitton: Virgil Abloh is a testament of a relationship that changed the course of fashion history. The version you will receive may be one of these two covers. It is not possible to choose it.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-louis-vuitton-virgil-abloh-english-version--R09018_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-louis-vuitton-virgil-abloh-english-version-books-and-stationery--R09018_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0501',
        name: 'Exercise Mat',
        price: '$2,390.00',
        detail: '70.1 x 26 x 0.2 inches (length x Height x Width)',
        intro: 'The Louis Vuitton exercise mat comes detailed with luxurious House signatures, including natural cowhide leather details and a Monogram canvas strap and card holder. The mat itself is supple to the touch and features a nonslip finish for safety.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-exercise-mat--GI0501_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-exercise-mat-sports-and-lifestyle--GI0501_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0797',
        name: 'Chess Game',
        price: '$4,600.00',
        detail: '11.9 x 1.4 x 11.9 inches (length x Height x Width)',
        intro: "The Chess Game recalls the recurring checkerboard theme seen across Virgil Abloh's work, most recently in the Spring-Summer 2022 collection. The transparent board can be removed and placed atop its Damier-patterned leather box during gameplay to give a floating effect. Ebony and boxwood chess pieces featuring the LV Initials and Monogram Flowers complete the set.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-chess-game--GI0797_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-chess-game-s00-sports-and-lifestyle--GI0797_PM1_Other%20view2.png?wid=1240&hei=1240',
    },
    {
        id: 'M10023',
        name: 'Courrier Lozine Carre Droite',
        price: '$42,500.00',
        detail: '22.2 x 20.5 x 22.2 inches (length x Height x Width)',
        intro: "Louis Vuitton's trunk craftsmanship is perpetuated in the square Malle Courrier Lozine Carre Gauche. Fashioned from Monogram canvas with traditional natural cowhide-leather trim, this hard case opens up to reveal two drawers and a lid lined with plush diamond-shaped quilting. This case opens to the right.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-courrier-lozine-carre-droite--M10023_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-courrier-lozine-carre-droite-monogram-trunks-and-travel--M10023_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0576',
        name: 'Porcelain Vase Petite Boite Chapeau',
        price: '$1,640.00',
        detail: '7.1 x 9.8 x 4.3 inches (length x Height x Width)',
        intro: 'The new Porcelain vase from the Home Decorating Collection presents a striking showcase for flowers. This standout piece takes the shape of the classic Louis Vuitton hat bag. It is crafted with great attention to detail, from the embossed Monogram pattern to the distinctive handle and name tag.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-porcelain-vase-petite-boite-chapeau--GI0576_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-porcelain-vase-petite-boite-chapeau-monogram-highlights--GI0576_PM1_Other%20view2.png?wid=1240&hei=1240',
    },
    {
        id: 'R96800',
        name: 'Ping-Pong Table Canvas domestic size',
        price: '$84,000.00',
        detail: 'Domestic table size : L 234 x W 130 x H 76 cm',
        intro: "The strikingly beautiful Louis Vuitton Ping-Pong Table brings a new elegance to sporting equipment, while paying homage to Louis Vuitton's trunkmaking savoir-faire. Covered in classic Monogram or Damier canvas, it has a playing surface bearing the Louis Vuitton Heritage stripes and initials, which can be also personalized. Alongside its crafted leather net perforated to create a lace-effect Monogram pattern, it also features leather straps that perfectly hold 10 Louis Vuitton balls and two drawers containing four bespoke rackets. Available in two sizes – professional and domestic – the Louis Vuitton Ping-Pong Table is the latest addition to the growing Louis Vuitton range of games tables, joining the Billiard and the Babyfoot.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-ping-pong-table-canvas-domestic-size--R96800_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-ping-pong-table-canvas-domestic-size-monogram-sports-and-lifestyle--R96800_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0746',
        name: 'James Ping Pong Set',
        price: '$2,280.00',
        detail: '10.6 x 2 x 6.3 inches (length x Height x Width)',
        intro: 'The exclusive design of the James ping pong set wins match point for prestige and functionality. This expertly crafted set of two table tennis rackets features a Monogram canvas cover and holder for four balls, which are also included. The zipper and wood handles both display an LV Circle.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-james-ping-pong-set--GI0746_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-james-ping-pong-set-monogram-sports-and-lifestyle--GI0746_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0838',
        name: 'Cup Louis',
        price: '$955.00',
        detail: '3.7 x 6.7 x 3.7 inches (length x Height x Width)',
        intro: "A charming addition to the House's Gift Collection, the Louis Monogram cup offers a stylish update to an everyday essential. This reusable porcelain cup is eco-friendly and features an inscribed Louis signature. A Monogram Canvas sleeve, featuring leather trim and a Louis Vuitton Show signature, is included for easy transport and comfortable use.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cup-louis--GI0838_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cup-louis-s00-home--GI0838_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R99967',
        name: 'Surface Lamp By Nendo',
        price: '$4,400.00',
        detail: '13.8 x 11.8 x 4.7 inches (length x Height x Width)',
        intro: 'With his Surface Lamp for the Objets Nomades collection, Oki Sato, the inspired designer behind the Nendo Studio: encased light in leather. A rechargeable lamp is shaped by a sheet of Nomade leather, perforated to reveal a subtle gradient interpretation of the emblematic Louis Vuitton Damier motif when the light is on. Between uses, it rolls up and fits into a handy carrying harness — “nomadism” at its best.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-surface-lamp-by-nendo--R99967_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-surface-lamp-by-nendo-home--R99967_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0727',
        name: 'Petite Malle Porcelain Vase',
        price: '$2,090.00',
        detail: '7.9 x 4.9 x 2.2 inches (length x Height x Width)',
        intro: "Inspired by the House's historic trunk collection, the Petite Malle Porcelain vase echoes the design of its iconic namesake. Signature details of the handbag, such as the Monogram pattern and S-lock hardware, are embossed on a delicate porcelain surface. This spring gift item is an elegant setting for the season's fresh blooms.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle-porcelain-vase--GI0727_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle-porcelain-vase-monogram-highlights--GI0727_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0824',
        name: 'Par Golf Towels Set',
        price: '$530.00',
        detail: '12.8 x 12.8 inches (length x Height)',
        intro: 'The Par Golf Towels set is a sleek companion for passionate golfers. Iconic House motifs, including a Louis Vuitton signature on the front and Monogram Flowers on the back, make these towels a stylish addition to any golf bag. A convenient leather strap and hook allow for portability, while a removable eyelet makes cleaning the pieces easy.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-par-golf-towels-set--GI0824_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-par-golf-towels-set-s00-sports-and-lifestyle--GI0824_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0825',
        name: 'Albatros Golf Head Covers',
        price: '$2,170.00',
        detail: '13 x 2 x 5.9 inches (length x Height x Width)',
        intro: 'Avid House fans can bring a touch of Louis Vuitton onto the course with the Albatros Golf Head covers. These pieces feature a mix of Monogram canvas and black leather, a nod to the Monogram Macassar design created by Virgil Abloh for the leather goods collection. The set includes three different-sized covers, each lined with shearling for an elegant finishing touch.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-albatros-golf-head-covers--GI0825_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-albatros-golf-head-covers-s00-sports-and-lifestyle--GI0825_PM1_Other%20view.png?wid=2048&hei=2048',
    },
    {
        id: 'GI0825',
        name: 'Albatros Golf Head Covers',
        price: '$2,170.00',
        detail: '2.1 x 5.4 x 2 inches (length x Height x Width)',
        intro: "Named after St. Andrews, one of the world's most prestigious golf clubs, the Black Monogram Andrews golf kit pays homage to the sport's legacy. The kit contains three golf balls featuring the LV Circle and four tees. For additional convenience, a polished hook clip allows this piece to be attached to a player's golf bag or belt loop.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-black-monogram-andrews-golf-kit--GI0826_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-black-monogram-andrews-golf-kit-monogram-sports-and-lifestyle--GI0826_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0518',
        name: 'FLASK HOLDER',
        price: '$2,090.00',
        detail: '2.8 x 9.1 x 2.8 inches (length x Height x Width)',
        intro: 'This eye-catching flask holder is a luxurious and practical piece inspired by the nomadic spirit of the House. The bottle itself is engraved with the Monogram pattern for a chic effect and keeps drinks warm or cool. It is protected by a Monogram canvas case with elegant natural cowhide details and a carrying strap.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-flask-holder--GI0518_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-flask-holder-monogram-sports-and-lifestyle--GI0518_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0876',
        name: 'Cups Set',
        price: '$1,160.00',
        detail: '3.5 x 3.5 x 3.5 inches/9 x 9 x 9 cm',
        intro: "Metallic gold-color bands bring additional elegance to this season's fine porcelain Cups set. Its joyful design exudes the vibrancy of Spring with a playful Monogram pattern and large LV Initials adorned with flowers. These four luxury tumblers are expertly crafted to the House's high standards, ensuring each sip from them is an indulgent experience.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cups-set--GI0876_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cups-set-s00-home--GI0876_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M47023',
        name: 'Coffret Trésor 24',
        price: '$5,300.00',
        detail: '9.4 x 6.3 x 4.7 inches (length x Height x Width)',
        intro: 'The medium-size treasure case combines the simplicity of Monogram canvas with the originality of a brightly coloured lining. It securely holds letters, jewellery or other small treasures.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tr%C3%A9sor-24--M47023_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tr%C3%A9sor-24-monogram-canvas-travel--M47023_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M99463',
        name: 'Hammock By Atelier Oï',
        price: '$48,500.00',
        detail: '135.8 x 15.7 x 38.6 inches (length x Height x Width)',
        intro: "A tour de force by the Atelier Oï design collective: their Hammock for the Objets Nomades collection takes the art of woven leather into a new dimension. Long strips of specially-developed Louis Vuitton leather are intertwined in a spectacular pattern and reinforced with 786 gilded engraved rivets. Elegant and comfortable, it's the most inviting spot to relax, in the garden, by the pool or even at the beach.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-hammock-by-atelier-o%C3%AF--M99463_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-hammock-by-atelier-o%C3%AF-home--M99463_PM1_Detail%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M10137',
        name: 'Coffret Trésor 24',
        price: '$5,300.00',
        detail: '9.4 x 5.1 x 6.7 inches (length x Height x Width)',
        intro: 'Like a rainbow, the Coffret Trésor is reinterpreted with colorful Tournesol lining, that will please any Hardsided collector.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tr%C3%A9sor-24--M10137_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tr%C3%A9sor-24-monogram-trunks-and-travel--M10137_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M10025',
        name: 'Courrier Lozine Carre Gauche',
        price: '$42,500.00',
        detail: '22.2 x 20.5 x 22.2 inches (length x Height x Width)',
        intro: "Louis Vuitton's trunk craftsmanship is perpetuated in the square Malle Courrier Lozine Carre Gauche. Fashioned from Monogram canvas with traditional natural cowhide-leather trim, this hard case opens up to reveal two drawers and a lid lined with plush diamond-shaped quilting. This case opens to the left.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-courrier-lozine-carre-gauche--M10025_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-courrier-lozine-carre-gauche-monogram-trunks-and-travel--M10025_PM1_Other4%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R97253',
        name: 'Lanterne GM By Zanellato and Bortotto',
        price: '$9,350.00',
        detail: '10.4 x 21.7 x 10.4 inches (length x Height x Width)',
        intro: "The LANTERNE By Zanellato / Bortotto GM is the result of a collaboration between Louis Vuitton and designers Giorgia Zanellato and Daniele Bortotto. This addition to the House's Objets Nomades collection celebrates artisanal craftsmanship with a meticulously woven honeycomb cage made of colorful leather, wood, and hardware. The portable item features a removable, rechargeable LED light with a frosted glass bulb.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lanterne-gm-by-zanellato-and-bortotto--R97253_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lanterne-gm-by-zanellato-and-bortotto-home--R97253_PM1_Ambiance%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M20251',
        name: 'Clutch Box',
        price: '$7,450.00',
        detail: '9.4 x 6.5 x 3.1 inches (length x Height x Width)',
        intro: "The Clutch Box men's bag in Monogram Eclipse canvas with black-leather trim and Ruthenium-color buckles was first seen at the Spring-Summer 2020 show. Compact yet roomy, it can fit most essentials inside its central zipped pocket and gusseted compartments. The black leather strap enables comfortable shoulder and cross-body carry.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-clutch-box--M20251_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-clutch-box-monogram-eclipse-canvas-trunks-and-travel--M20251_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0760',
        name: 'Vivienne Bride',
        price: '$3,100.00',
        detail: '6.7 x 2.4 x 7.9 inches/17 x 6 x 20 cm',
        intro: "The Vivienne bride is a charming collector's item for any House fan. To mark her union with Gaston, the iconic character is dressed for her wedding day, complete with a sparkling crystal tiara and colorful leather bouquet. The playful accessory is finished with emblematic signatures including the Monogram pattern on the legs and a Monogram Flower eye.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-vivienne-bride--GI0760_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-vivienne-bride-s00-sports-and-lifestyle--GI0760_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0761',
        name: 'Gaston Bridegroom',
        price: '$2,810.00',
        detail: '10 x 3 x 4.3 inches/24.5 cm x 7.5 cm x 11 cm',
        intro: 'The Gaston Bridegroom figurine sees the character in a full suit and top hat, dressed for his wedding to the beloved Vivienne. He is finished with polished Louis Vuitton stud eyes, an Essential V nose and vibrant Monogram Flower pins on his lapel. This intricately detailed figure is the perfect gift for those celebrating romance.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-gaston-bridegroom--GI0761_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-gaston-bridegroom-s00-sports-and-lifestyle--GI0761_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0839',
        name: 'Scott Box',
        price: '$1,130.00',
        detail: '14.0 x 12.5 x 9.0 cm/5.5 x 4.9 x 3.5 inches',
        intro: 'Plexiglass, rich leather and gleaming metal add up to an eye-catching ornamental box. With details that hark back to vintage House trunks, this glamorous new piece can be used to hold jewelry, makeup - or simply look stunning atop a dressing table.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-scott-box--GI0839_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-scott-box-s00-sports-and-lifestyle--GI0839_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0753',
        name: 'Dumbbells 2kg',
        price: '$2,640.00',
        detail: '6.3 x 3 x 7.3 inches (length x Height x Width)',
        intro: 'Sporty meets stylish with these eye-catching dumbbells, which combine functionality with luxurious House finishes. The 2kg weights are trimmed with the iconic Monogram canvas and finished with a Louis Vuitton signature and Monogram Flower engraving at the ends. The soft Epi leather handles are resistant to perspiration marks.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-dumbbells-2kg--GI0753_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-dumbbells-2kg-s00-sports-and-lifestyle--GI0753_PM1_Other%20view4.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0748',
        name: 'Christopher Jump Rope',
        price: '$810.00',
        detail: '59.1 x 3 x 0.4 inches (length x Height x Width)',
        intro: 'The Christopher jump rope adds a touch of luxury to daily workouts. Distinguished House touches include Epi leather and Monogram canvas that cover the front and back of the handles, which are accented by gleaming hardware. This sporty item features an innovative design that allows for the length of the rope to be adjusted.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-christopher-jump-rope--GI0748_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-christopher-jump-rope-monogram-sports-and-lifestyle--GI0748_PM1_Other%20view4.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0675',
        name: 'Exercise Mat',
        price: '$2,390.00',
        detail: '70.1 x 26 x 0.2 inches (length x Height x Width)',
        intro: '',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-exercise-mat--GI0675_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-exercise-mat-sports-and-lifestyle--GI0675_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R96714',
        name: 'Signature Sofa Outdoor By Frank Chou',
        price: '$65,000.00',
        detail: '296.5 x 78.4 x 90.3 cm (length x Height x Width)',
        intro: "With their flowing and delicate silhouette, the graceful arches of Frank Chou's Signature Armchair and Sofa recall elegant calligraphy brushstrokes and were inspired by terraced fields in Yunnan, China, and the naturally sculpted forms of Antelope Valley, Arizona, USA. This first Objet Nomade specifically designed for exterior use is upholstered with “Brio”, an innovative, colorful designed fabric from renowned Italian brand PAOLA LENTI. The Signature Sofa & Armchair are available in multiple color combinations and comfortably proportioned. The sofa’s three-meter length easily seats four people and is accompanied by the Signature Armchairs to form a complete seating set.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-signature-sofa-outdoor-by-frank-chou--R96714_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-signature-sofa-outdoor-by-frank-chou-home--R96714_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R08453',
        name: 'Louis Vuitton Catwalk, English version',
        price: '$75.00',
        detail: '10.9 x 7.5 inches/27.7 x 19.0 cm',
        intro: 'Founded in 1854, Louis Vuitton launched its first fashion collection in 1998. Unprecedented global fame ensued, as did pioneering high-profile collaborations with artists such as Takashi Murakami, Richard Prince, and Stephen Sprouse.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-louis-vuitton-catwalk-english-version--R08453_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-louis-vuitton-catwalk-english-version-books-and-stationery--R08453_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0796',
        name: 'Rug Vuitton',
        price: '$4,350.00',
        detail: '28 x 0.8 x 70.9 inches (length x Height x Width)',
        intro: "The handwoven Rug Vuitton brings the House's luxury craftsmanship to interior design. It features a bold graffiti-style Vuitton signature that stands out against a light-colored backdrop, making it a statement piece for any space. This welcoming rug is woven entirely from pure wool for a soft and warm finish.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-rug-vuitton--GI0796_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-rug-vuitton-s00-home-textile--GI0796_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M10064',
        name: 'Party Trunk',
        price: '$192,000.00',
        detail: '27.2 x 51.6 x 23.6 inches (length x Height x Width)',
        intro: 'Rooted in the House tradition to invent wine and spirits trunks, Louis Vuitton launches the Party Trunk. Keeping the spirit of the emblematic Louis Vuitton trunks, the Malle Party conveys a fresh and modern vibe, thanks to its colorful plexiglas panels, mirrors in the lids, and playful disco ball. The Party Trunk is the ideal home bar, it is also the perfect trunk to host a party with friends.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-party-trunk--M10064_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-party-trunk-monogram-eclipse-canvas-trunks-and-travel--M10064_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R98376',
        name: 'Belt Chair By Atelier Oï',
        price: '$12,100.00',
        detail: '21.7 x 33.1 x 22.4 inches (length x Height x Width)',
        intro: "The Belt Chair by the multifaceted designers of Atelier Oï embodies the essence of Louis Vuitton's expertise in fine leatherwork. High-precision cuts in eight broad strips of rich leather, stretched across a pale champagne-tone steel frame and buckled in back, create a smoothly undulating dune-like relief. Its comfort and stylish appeal have made this chair a great classic of the Objets Nomades collection.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-belt-chair-by-atelier-o%C3%AF--R98376_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-belt-chair-by-atelier-o%C3%AF-home--R98376_PM1_Other%20view6.png?wid=1240&hei=1240',
    },
    {
        id: 'R98737',
        name: 'Serpentine Table MM by Atelier Oï',
        price: '$38,500.00',
        detail: '65 x 28.7 x 65 inches (length x Height x Width)',
        intro: "Atelier Oï's newest addition to the Objets Nomades collection, the Serpentine Table was inspired by the intricate, flowing movements of traditional dances. The beveled glass top rests on a play of crisscrossing walnut legs held in place by finely worked straps of blue Louis Vuitton leather.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-serpentine-table-mm-by-atelier-oi--R98737_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-serpentine-table-mm-by-atelier-o%C3%AF-home--R98737_PM1_Closeup%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R98989',
        name: 'Diamond Sofa by Marcel Wanders studio',
        price: '$95,500.00',
        detail: '86.6 x 31.5 x 37.4 inches (length x Height x Width)',
        intro: "Experience the sensation of floating with the Diamond Sofa by Marcel Wanders studio. Made from curved slats of ash wood, the sofa base's elegantly arched shape creates a round cage from which the seats are suspended. These sculptural elements, combined with supple leather, result in a contemporary centerpiece for any gathering place.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-diamond-sofa-by-marcel-wanders-studio--R98989_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-diamond-sofa-by-marcel-wanders-studio-home--R98989_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R08873',
        name: 'Louis Vuitton Manufactures, English version',
        price: '$140.00',
        detail: '10 x 13 inches / 25 x 33 cm',
        intro: 'Louis Vuitton Manufactures illustrates the idea, fostered by the House, that a manufacture can be a place of fulfillment and individuality, where traditional craft skills can be learned, respected and transmitted, using age-old techniques and tools that would be familiar to the company’s founder. In pursuit of excellence, Louis Vuitton has scattered ateliers the length and breadth of France and beyond, to Geneva, the Veneto and even Texas. Often sites of historic interest or outstanding natural beauty will have a Louis Vuitton workshop nearby. Featuring exclusively commissioned photographs, this magnificent volume showcases the extraordinary locations and buildings, and the equally extraordinary artisans, that produce Louis Vuitton leather goods, fragrances, watches, shoes, high jewelry and ready-to-wear.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-louis-vuitton-manufactures-english-version--R08873_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-louis-vuitton-manufactures-english-version-books-and-stationery--R08873_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R96108',
        name: 'Spiral Lamp GM By Atelier Oï',
        price: '$15,300.00',
        detail: '15 x 57.1 x 15 inches (length x Height x Width)',
        intro: "More than a lighting accessory, the Spiral Lamp by the architect-designers of Atelier Oï for Louis Vuitton's Objets Nomades collection is an endless interplay of light and shadow. Thirty-two strips of twisted leather, natural on one side and metallic on the other, reflect and direct the light of two LED bulbs. A movable central ring changes the configuration to multiply the possibilities of dialogue with the décor.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-spiral-lamp-gm-by-atelier-o%C3%AF--R96108_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-spiral-lamp-gm-by-atelier-o%C3%AF-home--R96108_PM1_Ambiance%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0799',
        name: 'LV Flower Skateboard',
        price: '$2,580.00',
        detail: '8.3 x 31.5 x 3.9 inches (length x Height x Width)',
        intro: "The LV Flower skateboard is a fresh new collector's item featuring an eye-catching design on either side. The underside of the wood deck displays the LV Floral pattern, while the grip contrasts with a graphic take on the LV Initials. Louis Vuitton signatures on the wheels and a special made-to-measure box complete this statement piece.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-flower-skateboard--GI0799_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-flower-skateboard-sports-and-lifestyle--GI0799_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M20087',
        name: 'Malle Vendôme',
        price: '$139,000.00',
        detail: '24.4 x 55.1 x 21.7 inches (length x Height x Width)',
        intro: 'To celebrate the opening of the new Louis Vuitton boutique on the famous Place Vendôme, birthplace of Parisian jewellers, the House imagined a sumptuous trunk to host and enhance the beauty and pureness of high jewellery pieces.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-malle-vend%C3%B4me--M20087_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-malle-vend%C3%B4me-monogram-travel--M20087_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R97491',
        name: 'Bulbo By Campana Brothers',
        price: '$102,000.00',
        detail: '51.2 x 59.1 x 51.2 inches (length x Height x Width)',
        intro: "Like a strange and wonderful tropical flower, the Campana Brothers' nest rises to envelop the sitter as if in an affectionate embrace. Each of its layered petals is lined with elegant Louis Vuitton leather on the outside and an inviting, warming fabric on the inside for absolute comfort.To stretch out or curl up in the nest is to discover a haven that feels created for luxuriant wellbeing, generously spacious for one person and cosy and loving for two.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-bulbo-by-campana-brothers--R97491_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-bulbo-by-campana-brothers-home--R97491_PM1_Closeup%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R98539',
        name: 'Dolls by Raw Edges',
        price: '$19,700.00',
        detail: '25.6 x 25.6 x 17.7 inches (length x Height x Width)',
        intro: 'This Dolls limited-edition chair is designed by award-winning design studio Raw Edges, Yael Mer and Shay Alkalay. Characterized by a playful aesthetic, this eclectic piece comprises three finely crafted elements - a base and seat in rich yellow and a delicately sculpted shell in white leather. The finishes adorning the shells and seats of the chair family draw inspiration from different world cultures.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-dolls-by-raw-edges--R98539_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-dolls-by-raw-edges-leather-other-material-home--R98539_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R98764',
        name: 'Anemona Table GM by Atelier Biagetti',
        price: '$107,000.00',
        detail: '106.3 x 29.1 x 55.1 inches (length x Height x Width)',
        intro: 'The Italian artist-designer duo behind Atelier Biagetti pays homage to the Adriatic Sea in their Anemona Table for the Objets Nomades collection. Under the beveled glass top, the sculptural, wave-like base is lined with sumptuous Louis Vuitton leather.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-anemona-table-gm-by-atelier-biagetti--R98764_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-anemona-table-gm-by-atelier-biagetti-home--R98764_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0578',
        name: 'PM Speaker Trunk',
        price: '$11,800.00',
        detail: '9.3 x 6.7 x 3.5 inches (length x Height x Width)',
        intro: "The PM Speaker Trunk, inspired by Virgil Abloh's love of music, also reflects the attitude of the Spring-Summer 2022 Taurillon leather Illusion theme. The classic truck-shaped case houses a speaker and is adorned with an embossed Monogram print in a bold tie-dye design. Impeccable detailing includes Monogram Flower screws and a durable leather carrying strap.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pm-speaker-trunk--GI0578_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pm-speaker-trunk-s00-sports-and-lifestyle--GI0578_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0901',
        name: 'Summer Capsule Scott Box',
        price: '$1,320.00',
        detail: '5.5 x 3.5 x 4.9 inches (length x Height x Width)',
        intro: 'Part of the Louis Vuitton Summer collection, this version of the iconic Scott box comes in transparent Plexiglas with a multicolored Monogram print. Ideal to hold jewelry, makeup and other small items, or simply as a decorative element, this vibrant piece is finished with emblematic details, including leather trim and an S-lock closure.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-summer-capsule-scott-box--GI0901_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-summer-capsule-scott-box-s00-sports-and-lifestyle--GI0901_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'R96371',
        name: 'Aguacate by Campana Brothers',
        price: '$58,000.00',
        detail: '117.3 x 110 x 1.2 inches (length x Height x Width)',
        intro: "From Brazil's internationally acclaimed Campana Brothers comes the Aguacate Multicolore, a limited-edition sculptural object that brings a burst of radiance to any space. Nine differently sized pieces can be configured as desired and mounted on the wall or suspended from the ceiling. This nature-inspired piece is masterfully woven by hand and adorned by the artists' signatures and discreet House branding.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-aguacate-by-campana-brothers--R96371_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-aguacate-by-campana-brothers-home--R96371_PM1_Closeup%20view.png?wid=1240&hei=1240',
    },
];

export default products;
