const contentImg = [
    {
        src: 'https://us.louisvuitton.com/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-1.png?imwidth=216%20216w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-1.png?imwidth=320%20320w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-1.png?imwidth=456%20456w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-1.png?imwidth=656%20656w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-1.png?imwidth=824%20824w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-1.png?imwidth=1080%201080w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-1.png?imwidth=1240%201240w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-1.png?imwidth=2048%202048w',
        alt: 'img1',
    },
    {
        src: 'https://us.louisvuitton.com/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-5.png?imwidth=216%20216w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-5.png?imwidth=320%20320w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-5.png?imwidth=456%20456w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-5.png?imwidth=656%20656w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-5.png?imwidth=824%20824w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-5.png?imwidth=1080%201080w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-5.png?imwidth=1240%201240w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-5.png?imwidth=2048%202048w',
        alt: 'img2',
    },
    {
        src: 'https://us.louisvuitton.com/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-3.png?imwidth=216%20216w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-3.png?imwidth=320%20320w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-3.png?imwidth=456%20456w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-3.png?imwidth=656%20656w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-3.png?imwidth=824%20824w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-3.png?imwidth=1080%201080w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-3.png?imwidth=1240%201240w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-3.png?imwidth=2048%202048w',
        alt: 'img3',
    },
    {
        src: 'https://us.louisvuitton.com/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-4.png?imwidth=216%20216w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-4.png?imwidth=320%20320w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-4.png?imwidth=456%20456w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-4.png?imwidth=656%20656w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-4.png?imwidth=824%20824w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-4.png?imwidth=1080%201080w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-4.png?imwidth=1240%201240w,%20/content/dam/lv/online/high-end/unisex/collection/lady-b/U_LP_Lady_B_Drop_2_v1.html/jcr:content/assets/visionary/visionary-bubble-4.png?imwidth=2048%202048w',
        alt: 'img-4',
    },
];

export default contentImg;
