const products = [
    {
        id: 'M22515',
        name: 'Twist PM',
        price: '$4,550.00',
        detail: '7.5 x 5.9 x 3.5 inches (Length x height x width)',
        intro: 'The Twist PM handbag in Epi grained leather features a tricolor, embroidered strap with Monogram Blossoms on one side and a small version of the Monogram pattern on the other. In addition to bringing a playful feel to the bag, the strap, together with the removable leather handle, gives numerous carry options.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-pm--M22515_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-pm-epi-leather-handbags--M22515_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22098',
        name: 'Twist PM',
        price: '$4,700.00',
        detail: '7.5 x 5.9 x 3.5 inches (Length x height x width)',
        intro: 'Made from Epi grained leather, the Twist PM handbag takes on an edgy feel with an iridescent triple chain. The chain can be used for hand carry or attached to the removable leather strap for shoulder and cross-body wear. The iconic Twist lock features the same shimmery metallic finish as the triple chain.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-pm--M22098_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-pm-epi-leather-handbags--M22098_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22029',
        name: 'Twist MM',
        price: '$5,000.00',
        detail: '9.1 x 6.7 x 3.7 inches (Length x height x width)',
        intro: 'This Twist MM handbag in Epi grained leather is adorned with a unique triple chain that enables hand-carry, but also shoulder and cross-body wear when two of the thin chains are attached to the leather strap. The triple chain and LV Twist lock feature an iridescent finish that makes them shimmer like a scarab beetle.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-mm--M22029_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-mm-epi-leather-handbags--M22029_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22028',
        name: 'Twist MM',
        price: '$5,000.00',
        detail: '9.1 x 6.7 x 3.7 inches (Length x height x width)',
        intro: 'This Twist MM handbag in Epi grained leather is adorned with a unique triple chain that enables hand-carry, but also shoulder and cross-body wear when two of the thin chains are attached to the leather strap. The triple chain and LV Twist lock feature an iridescent finish that makes them shimmer like a scarab beetle.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-mm--M22028_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-mm-epi-leather-handbags--M22028_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82289',
        name: 'Pochette Coussin',
        price: '$2,840.00',
        detail: '7.9 x 5.5 x 3.1 inches (Length x height x width)',
        intro: 'The Pochette Coussin is crafted from puffy lambskin, embossed with the Monogram pattern in a delicate colorway, for a feminine cushiony bag. The supple, body-friendly shape of the Coussin makes it a delight. A removable chain, decorated with an LV Circle, enables a variety of carry options: clutch, shoulder or belt.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-coussin--M82289_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-coussin-h27-small-leather-goods--M82289_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22398',
        name: 'Coussin PM',
        price: '$4,700.00',
        detail: '10.2 x 7.9 x 4.7 inches (Length x height x width)',
        intro: 'For Spring 2023 the Coussin PM handbag is arrayed in a luminous seasonal colorway. Fashioned from pillowy lambskin embossed with Monogram motifs, this edition will enliven any warm-weather silhouette. The bag’s chunky golden chain is perfect for an over-the-shoulder carry, while the wide textile strap can be styled for cross-body wear.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coussin-pm--M22398_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coussin-pm-h27-handbags--M22398_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82210',
        name: 'Wallet on Chain Ivy',
        price: '$1,900.00',
        detail: '9.3 x 4.7 x 1.7 inches (Length x height x width)',
        intro: 'The on-trend Wallet on Chain Ivy is made from grained Monogram Empreinte leather, embossed with an oversized Monogram motif. The perfect day-to-evening companion, it can be carried as a clutch, worn close to the shoulder with its short gold-color chain, or for a more casual attitude, carried cross-body thanks to its removable and adjustable leather strap.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-wallet-on-chain-ivy--M82210_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-wallet-on-chain-ivy-monogram-empreinte-leather-small-leather-goods--M82210_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M81911',
        name: 'Wallet on Chain Ivy',
        price: '$1,760.00',
        detail: '9.3 x 4.7 x 1.7 inches (Length x height x width)',
        intro: "Inspired by the Sac Recoleta handbag from the 2000's, the on-trend Wallet On Chain Ivy bag is fashioned from Monogram canvas. The removable gold-color chain allows short-shoulder carry while the adjustable and detachable strap, in natural leather, enables cross-body and long-shoulder carry. Three card slots and a zipped inside pocket make it perfect for everyday essentials.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-wallet-on-chain-ivy--M81911_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-wallet-on-chain-ivy-monogram-small-leather-goods--M81911_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46581',
        name: 'Néonoé BB',
        price: '$1,900.00',
        detail: '7.9 x 7.9 x 5.1 inches (Length x height x width)',
        intro: "The NéoNoé BB in Monogram canvas with natural leather trim is a smaller interpretation of the House's iconic NéoNoé bucket bag. Spacious enough to hold essentials such as keys, Airpods, and an iPhone, it features a leather drawstring to close the bag and keep belongings secure. A removable handle and detachable, adjustable strap offer multiple carry options.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-n%C3%A9ono%C3%A9-bb--M46581_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-n%C3%A9ono%C3%A9-bb-monogram-handbags--M46581_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46526',
        name: 'Néonoé BB',
        price: '$2,710.00',
        detail: '10.2 x 10.2 x 6.9 inches (Length x height x width)',
        intro: "The House's emblematic bucket bag, the NéoNoé MM, is fashioned from luminous cream-color Monogram Empreinte leather, making it stylish no matter the season. The cream-color microfiber lining and Monogram Flowers and LVs discretely embossed into the leather bring understated charm. A top handle and leather shoulder strap offer a variety of carry options.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-n%C3%A9ono%C3%A9-mm--M46526_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-n%C3%A9ono%C3%A9-mm-monogram-empreinte-leather-handbags--M46526_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46055',
        name: 'Cluny Mini',
        price: '$2,280.00',
        detail: '7.9 x 6.3 x 3 inches (Length x height x width)',
        intro: 'The adorable Cluny Mini handbag in iconic Monogram canvas is designed to delight LV lovers. A perfect little bag for daily wear, it features a signature Toron handle and key bell in the Maison\'s classic natural leather. A textile strap enriched with a woven "Louis Vuitton" can be added or detached, thus enhancing the bag\'s versatility.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cluny-mini--M46055_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cluny-mini-monogram-handbags--M46055_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M42738',
        name: 'Cluny BB',
        price: '$2,440.00',
        detail: '11 x 7.9 x 3.9 inches (Length x height x width)',
        intro: 'A colorful leather strap lends a lively twist to this Cluny BB handbag, crafted from classic Monogram canvas. Worn cross-body or carried in ladylike fashion by its top handle, this timeless bag is designed for busy lifestyles. It opens wide for easy access to the smartly organized interior, while the magnetic flap and zipped inner pocket keep belongings secure.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cluny-bb--M42738_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cluny-bb-monogram-handbags--M42738_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46503',
        name: 'Trianon PM',
        price: '$3,050.00',
        detail: '11 x 7.1 x 3.1 inches (Length x height x width)',
        intro: 'With its more compact format and multiple zipped compartments, this Trianon PM handbag in embossed Monogram Empreinte leather is the perfect alternative to the traditional tote. Its V-cut lines are inspired by the emblematic Louis Vuitton Pallas bag. Two top handles, as well as a detachable shoulder strap, make it comfortable to carry.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm--M46503_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm-monogram-empreinte-leather-handbags--M46503_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46585',
        name: 'Trianon PM',
        price: '$3,150.00',
        detail: '11 x 7.1 x 3.1 inches (Length x height x width)',
        intro: 'The Trianon PM tote, with its distinctive V-cut silhouette, is made from grained Monogram Empreinte leather with the Monogram Flowers and LVs embossed then printed on the leather in a soft cream tone. A long adjustable and removable strap, in addition to the two top handles, give carry options.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm--M46585_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm-monogram-empreinte-leather-handbags--M46585_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46504',
        name: 'Trianon MM',
        price: '$3,150.00',
        detail: '14.2 x 8.7 x 3.5 inches (Length x height x width)',
        intro: 'Made from Monogram Empreinte leather, with its embossed Giant Monogram pattern, the Trianon MM tote is an elegant and functional bag. Two rolled-leather top handles ensure comfortable hand carry while a detachable and adjustable leather strap enable shoulder and cross-body wear. The MM size is roomy enough for daily essentials.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-mm--M46504_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-mm-monogram-empreinte-leather-handbags--M46504_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46488',
        name: 'Trianon PM',
        price: '$3,050.00',
        detail: '11 x 7.1 x 3.1 inches (Length x height x width)',
        intro: 'With its more compact format and multiple zipped compartments, this Trianon PM handbag in embossed Monogram Empreinte leather is the perfect alternative to the traditional tote. Its V-cut lines are inspired by the emblematic Louis Vuitton Pallas bag. Two top handles, as well as a detachable shoulder strap, make it comfortable to carry.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm--M46488_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm-monogram-empreinte-leather-handbags--M46488_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46487',
        name: 'Trianon MM',
        price: '$3,150.00',
        detail: '14.2 x 8.7 x 3.5 inches (Length x height x width)',
        intro: 'Made from Monogram Empreinte leather, with its embossed Giant Monogram pattern, the Trianon MM tote is an elegant and functional bag. Two rolled-leather top handles ensure comfortable hand carry while a detachable and adjustable leather strap enable shoulder and cross-body wear. The MM size is roomy enough for daily essentials.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-mm--M46487_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-mm-monogram-empreinte-leather-handbags--M46487_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M21614',
        name: 'New Wave Chain Bag GM',
        price: '$3,300.00',
        detail: '5.5 x 14.2 x 10.6 inches (Length x height x width)',
        intro: 'The quilted Chain Bag New Wave now comes in glamourous XL proportions: the New Wave Chain Bag GM. Generous yet refined, it incarnates a vision of uptown chic. The V-shape quilting and vintage treatment of the gold-color LV Initials make it instantly recognizable. A sliding chain, passing through engraved eyelets, enables shoulder and cross-body carry.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-new-wave-chain-bag-gm--M21614_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-new-wave-chain-bag-gm-h24-handbags--M21614_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M21796',
        name: 'New Wave Chain Bag GM',
        price: '$3,300.00',
        detail: '5.5 x 14.2 x 10.6 inches (Length x height x width)',
        intro: 'The quilted Chain Bag New Wave now comes in glamourous XL proportions: the New Wave Chain Bag GM. Generous yet refined, it incarnates a vision of uptown chic. The V-shape quilting and vintage treatment of the gold-color LV Initials make it instantly recognizable. A sliding chain, passing through engraved eyelets, enables shoulder and cross-body carry.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-new-wave-chain-bag-gm--M21796_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-new-wave-chain-bag-gm-h24-handbags--M21796_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M21615',
        name: 'New Wave Chain Bag GM',
        price: '$3,300.00',
        detail: '5.5 x 14.2 x 10.6 inches (Length x height x width)',
        intro: 'The quilted Chain Bag New Wave now comes in glamourous XL proportions: the New Wave Chain Bag GM. Generous yet refined, it incarnates a vision of uptown chic. The V-shape quilting and vintage treatment of the gold-color LV Initials make it instantly recognizable. A sliding chain, passing through engraved eyelets, enables shoulder and cross-body carry.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-new-wave-chain-bag-gm--M21615_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-new-wave-chain-bag-gm-h24-handbags--M21615_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'N40471',
        name: 'Neverfull MM',
        price: '$2,370.00',
        detail: '12.2 x 11 x 5.5 inches (Length x height x width)',
        intro: 'This Neverfull MM tote bag is made from Damier Azur coated canvas customized with a bold five-color nautical print of ropes and chains, bringing a fresh twist to the classic checkerboard pattern. This versatile bag features side laces that can be cinched for a sleeker silhouette or loosened for a more casual look.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-neverfull-mm--N40471_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-neverfull-mm-damier-azur-handbags--N40471_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'N40472',
        name: 'Alma BB',
        price: '$2,100.00',
        detail: '9.3 x 6.9 x 4.5 inches (Length x height x width)',
        intro: 'The Art-Deco lines of this Alma BB handbag are revisited in a unique version of Damier Azur canvas featuring a nautical print of ropes and chains. Ideal for a weekend at the Hamptons, the Alma is equipped with a removable and adjustable strap, in addition to top handles, for cross-body carry.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-alma-bb--N40472_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-alma-bb-damier-azur-handbags--N40472_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'N40473',
        name: 'Speedy Bandoulière 25',
        price: '$2,150.00',
        detail: '9.8 x 7.5 x 5.9 inches (Length x height x width)',
        intro: 'The Speedy Bandoulière 25 handbag gets a summery makeover in Damier Azur canvas decorated with a bold nautical print. The 5-color serigraphy of chains and ropes with golden highlights brings a distinct resort feel to the bag. Two rolled-leather top handles and a removable and adjustable strap give carry options.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-speedy-bandouli%C3%A8re-25--N40473_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-speedy-bandouli%C3%A8re-25-damier-azur-handbags--N40473_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'N41374',
        name: 'Speedy Bandoulière 25',
        price: '$1,820.00',
        detail: '9.8 x 7.5 x 5.9 inches (Length x height x width)',
        intro: 'The Speedy Bandoulière 25 handbag in fresh Damier Azur canvas is an ideal choice for summer in the city. Originally created for travelers in the 1930s - the name refers to the era’s rapid transit – every feature of the Speedy’s design is iconic, from its unmistakable shape to the rolled leather handles, engraved padlock and detachable strap.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-speedy-bandouli%C3%A8re-25--N41374_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-speedy-bandouli%C3%A8re-25-damier-azur-handbags--N41374_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22273',
        name: 'Petite Malle',
        price: '$6,150.00',
        detail: '7.9 x 4.9 x 2.4 inches (Length x height x width)',
        intro: 'This Petite Malle handbag in calfskin is embossed with the Nanogram, a playfully proportioned Monogram pattern. The motif printed on the soft leather is of a slightly lighter color than the leather base, giving it a refined aspect. The Petit Malle can be carried as a clutch or worn with its removable and adjustable leather strap. This Petite Malle is adorned with exaggerated edges and rounded corners, as a playful twist on this iconic shape.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle--M22273_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle-h27-handbags--M22273_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M45943',
        name: 'Petite Malle',
        price: '$5,700.00',
        detail: '7.9 x 4.9 x 2.4 inches (Length x height x width)',
        intro: 'Every detail of the Petite Malle handbag is inspired by the history of Louis Vuitton trunks: the shape, the iconic Monogram canvas, the gold-tone lock and fittings – even the sheepskin lining reprises a classic House motif. Impeccably crafted, with smooth calfskin trim, this covetable “little trunk” travels easily from day to evening. It can be carried as a clutch or attached to the adjustable strap for cross-body wear.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle--M45943_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle-monogram-handbags--M45943_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M21462',
        name: 'Petite Malle',
        price: '$6,800.00',
        detail: '7.9 x 4.9 x 2.4 inches (Length x height x width)',
        intro: 'This season, the Petite Malle is offered in a fresh iteration of the signature House motif. New Monogram Jacquard Denim features a deliberately raw, stone-washed effect, providing a lively contrast to the bag’s black leather trim, gleaming hardware and exclusive gothic chain. This fashionable “little trunk” can be carried as a clutch or worn on its removable leather strap.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle--M21462_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle-autres-toiles-monogram-handbags--M21462_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M20764',
        name: 'Petite Malle',
        price: '$5,700.00',
        detail: '7.9 x 4.9 x 2.4 inches (Length x height x width)',
        intro: 'Part of the LV Match capsule, a salute to Grand Slam tennis, this Petite Malle handbag is made from puffy, Monogram embossed lambskin. White calfskin trim contrasts with the terracotta leather, a nod to the lines on a clay court. Fun and fashionable, this luxurious “little trunk” can be carried as a clutch or worn on its detachable strap.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle--M20764_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-petite-malle-h27-handbags--M20764_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22494',
        name: 'Comet Bumbag',
        price: '$3,150.00',
        detail: '17.7 x 6.7 x 3.5 inches (Length x height x width)',
        intro: 'The supple calf leather brings a sporty modernity to the shape of the Comet Bumbag. The calfskin features the Monogram Spotlight print in which the Monogram Blossoms and LVs seem to cast vivid neon shadows. The two zipped front pockets make it practical while the adjustable strap and top handle allow many different carry options.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-comet-bumbag--M22494_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-comet-bumbag-other-leathers-bags--M22494_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22495',
        name: 'Comet Messenger PM',
        price: '$2,980.00',
        detail: '8.5 x 5.5 x 3 inches (Length x height x width)',
        intro: 'The Comet Messenger PM is a compact messenger bag made from calfskin with a multiple-exposure version of the Monogram print in vivid purple and neon green. The gradation of hues across the leather almost makes it look as if the bag was lit by a spotlight. Double zip closure means belongings stay secure but easily accessible.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-comet-messenger-pm--M22495_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-comet-messenger-pm-other-leathers-bags--M22495_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22488',
        name: 'Comet Backpack',
        price: '$4,200.00',
        detail: '14.6 x 16.9 x 6.7 inches (Length x height x width)',
        intro: 'The sporty Comet Backpack is crafted from supple calf leather featuring a unique version of the Monogram motif, in which the Monogram Flowers and LVs seem to throw vivid neon shadows. This backpack has an outside front zipped pocket and two side zipped pockets for quick access to belongings.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-comet-backpack--M22488_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-comet-backpack-other-leathers-bags--M22488_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22634',
        name: 'Meteor Travel Bag 50',
        price: '$4,950.00',
        detail: '18.5 x 15 x 7.5 inches (Length x height x width)',
        intro: "Inspired by the Astralis Bag from the House' archives, the Meteor Travel Bag 50 in calf leather embodies the spirit of modern travel. It features a unique Monogram print which seems to radiate variations of itself in vivid neon colors. Long top handles and a removable and adjustable jacquard textile strap give carry options.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-meteor-travel-bag-50--M22634_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-meteor-travel-bag-50-other-leathers-travel--M22634_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M43735',
        name: 'Christopher PM',
        price: '$3,300.00',
        detail: '15 x 17.3 x 8.3 inches (Length x height x width)',
        intro: "The Christopher PM conjures up the rugged spirit of a hiking pack in Monogram canvas. It's equally chic at work and play and evokes a fine lifestyle.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-christopher-pm--M43735_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-christopher-pm-monogram-macassar-canvas-travel--M43735_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M45935',
        name: 'Handle Soft Trunk',
        price: '$3,300.00',
        detail: '8.5 x 5.9 x 2.8 inches (Length x height x width)',
        intro: "Crafted in Louis Vuitton's emblematic Monogram Macassar canvas, the Handle Soft Trunk evokes the House's heritage as a luggage maker with sophisticated details like the riveted corners and leather reinforcement strips. Its slim profile and removable strap make it effortless to carry, and it opens wide for easy access. Ideal for small digital devices and other personal essentials.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-handle-soft-trunk--M45935_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-handle-soft-trunk-monogram-macassar-canvas-bags--M45935_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46327',
        name: 'Avenue Slingbag',
        price: '$2,090.00',
        detail: '7.9 x 12.2 x 2.8 inches (Length x height x width)',
        intro: 'This redesign of the Avenue Slingbag features new crafted details and a more sustainable design, thanks to its canvas strap and interior lining. Made from Monogram Macassar canvas with black-leather trim, it exudes masculine elegance. The front zipped pocket and small zipped pocket on top of the bag make this Avenue Slingbag practical.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-avenue-slingbag--M46327_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-avenue-slingbag-monogram-macassar-canvas-bags--M46327_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M45557',
        name: 'Magnetic Messenger',
        price: '$1,760.00',
        detail: '12.4 x 8.7 x 3.1 inches (Length x height x width)',
        intro: 'Inspired by the brown-and-black stripes of Macassar Ebony wood, the Monogram Macassar Magnetic Messenger bag pairs Monogram canvas with black leather and matte-black hardware. Its boxy shape and body-friendly design make it the stylish choice for an everyday bag. The adjustable strap delivers carrying comfort while numerous pockets bring practicality.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-magnetic-messenger--M45557_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-magnetic-messenger-monogram-macassar-canvas-bags--M45557_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M81972',
        name: 'LV x YK Gaston Wearable Wallet',
        price: '$2,290.00',
        detail: '8.7 x 5.7 x 1.8 inches (Length x height x width)',
        intro: "On-trend and practical, the LVxYK Gaston wearable wallet joins the “Pumpkins” theme of the Louis Vuitton x Yayoi Kusama collection with a vibrant new look. The venerated Japanese artist's iconic pumpkins are printed in bright colors on Monogram Eclipse Reverse canvas. And it comes with a removable pumpkin-shaped pouch, perfect for coins and contactless payment cards.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-gaston-wearable-wallet--M81972_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-gaston-wearable-wallet-monogram-eclipse-canvas-bags--M81972_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46440',
        name: 'LV x YK Discovery Backpack',
        price: '$3,250.00',
        detail: '11.8 x 15.7 x 7.9 inches (Length x height x width)',
        intro: "The LVxYK Discovery Backpack gets a creative new treatment as part of the second major Louis Vuitton x Yayoi Kusama collection. Monogram Eclipse Reverse canvas is enlivened with a colorful print featuring one of the renowned artist's emblematic images: stylized pumpkins arrayed with psychedelic dots. A practical, user-friendly backpack, and a celebration of the House's timeless bond with the art world.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-discovery-backpack--M46440_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-discovery-backpack-monogram-eclipse-canvas-bags--M46440_PM1_Cropped%20worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46436',
        name: 'LV x YK Maxi Bumbag',
        price: '$2,720.00',
        detail: '17.3 x 9.4 x 2.8 inches (Length x height x width)',
        intro: 'For the second exclusive Louis Vuitton x Yayoi Kusama collection, the LVxYK Maxi Bumbag is enlivened with a trio of colorful pumpkins. The celebrated Japanese artist has been creating images of pumpkins since childhood, enchanted by their winsome form and human-like warmth. Styled in Monogram Eclipse Reverse canvas, this hands-free carrier is a practical accessory with a fun creative look.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-maxi-bumbag--M46436_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-maxi-bumbag-monogram-eclipse-canvas-bags--M46436_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46439',
        name: 'LV x YK Keepall 55',
        price: '$3,400.00',
        detail: '21.7 x 12.2 x 10.2 inches (Length x height x width)',
        intro: "The Louis Vuitton x Yayoi Kusama collection features a vibrant update of a House classic: the LVxYK Keepall 55 is crafted in Monogram Eclipse Reverse canvas adorned with colorful pumpkins, an emblematic theme in Kusama's work. The venerated artist began drawing pumpkins as a child, later using them in her paintings and sculptures as a symbol of warmth and reassurance. Here they transform a practical bag into an artistic collector's piece.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-keepall-55--M46439_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-maxi-bumbag-monogram-eclipse-canvas-bags--M46436_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'N98247',
        name: 'Mini Soft Trunk',
        price: '$22,200.00',
        detail: '7.3 x 5.1 x 3.1 inches (Length x height x width)',
        intro: 'In rare and precious crocodilien skin, this Mini Soft Trunk is a testament to exceptional leather craftsmanship. It takes its style cues, such as its revited corners and boxy shape, from classic luggage found in the Louis Vuitton archives. The two chains, one connected to the zipper and the other serving as part of the shoulder strap, bring modernity to this small bag.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mini-soft-trunk--N98247_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mini-soft-trunk-crocodilien-mat-bags--N98247_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'N82245',
        name: 'Mini Soft Trunk',
        price: '$9,800.00',
        detail: '7.3 x 5.1 x 3.1 inches (Length x height x width)',
        intro: "For 2023, the Mini Soft Trunk comes in a striking new mix of materials, crafted in sumptuous black ostrich leather with a calfskin lining. Its angular design and reinforced corners were inspired by the House's heritage as a trunk maker, enhanced by a distinctive chain detail. A spacious, practical city bag that makes a sophisticated statement.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mini-soft-trunk--N82245_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mini-soft-trunk-ostrich-leather-bags--N82245_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'N82042',
        name: 'Mini Soft Trunk',
        price: '$26,100.00',
        detail: '7.3 x 5.1 x 3.1 inches (Length x height x width)',
        intro: "The SS23 exotic collection fully reflects Louis Vuitton Men identity with an exclusive Gradient Fluo matte crocodile finish, echoing to Virgil's palette of primary colors. This exclusive finishing played in pop and fluo colors is a handmade and complex finishing as there are several phases in the creative process. From dyeing to sanding, the skin is manually sprayed to make it look like it has been painted by hand. Once again, this long technique makes every bag unique and showcases the incredible know-how and expertise of the House on exotics skins.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mini-soft-trunk--N82042_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mini-soft-trunk-crocodilien-mat-bags--N82042_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'N82241',
        name: 'S-Lock Sling Bag',
        price: '$26,800.00',
        detail: '8.3 x 5.9 x 1.6 inches (Length x height x width)',
        intro: 'The casual, sporty spirit of the S-Lock Sling Bag gets a sophisticated update for 2023, crafted in sumptuous black alligator with calfskin details. The distinctive scale pattern of the leather is highlighted by a signature S-lock closure that keeps the contents securely in place. Designed for cross-body or hand carry, this on-trend bag makes a stylish statement.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-s-lock-sling-bag--N82241_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-s-lock-sling-bag-crocodilien-mat-bags--N82241_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46404',
        name: 'LV x YK Sac Plat',
        price: '$3,800.00',
        detail: '14.4 x 15 x 3.5 inches (Length x height x width)',
        intro: "The LVxYK Sac Plat is part of the second Louis Vuitton x Yayoi Kusama collection, an exceptional collaboration uniting the House's know-how with the vision of a world-class artist. For this simple but functional carryall, Monogram Eclipse canvas is enlivened with Kusama's signature dots in shades of gray, screen-printed for a 3D hand-painted effect. A practical, spacious city bag, and a timeless collector's item.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-sac-plat--M46404_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-sac-plat-monogram-eclipse-canvas-bags--M46404_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M45734',
        name: 'Weekend Tote PM',
        price: '$2,780.00',
        detail: '14.6 x 11.4 x 5.1 inches (Length x height x width)',
        intro: "The Week-End Tote in Monogram Macassar canvas is inspired by Louis Vuitton's historic Week-End bag. Perfect for a day in the city or a weekend getaway, it offers a high-capacity main compartment plus a handy outside phone pocket. And it's easy to carry with its adjustable strap and flat handles that fit comfortably on the shoulder.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-weekend-tote-pm--M45734_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-weekend-tote-pm-monogram-macassar-canvas-bags--M45734_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M57308',
        name: 'Takeoff Tote',
        price: '$3,250.00',
        detail: '14.4 x 13.4 x 5.1 inches (Length x height x width)',
        intro: 'Styled in soft, finely grained black calf leather, the LV Aerogram Takeoff Tote is a practical and elegant outsized bag. Its minimalist design is sure to appeal to the fashion-conscious man who appreciates subtle signature touches like the leather tag and LV initials in black metal. And it has a lockable compartment to keep a laptop and other valuables secure.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-takeoff-tote--M57308_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-takeoff-tote-lv-aerogram-bags--M57308_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M30811',
        name: 'Vertical Tote',
        price: '$3,300.00',
        detail: '12.6 x 14.6 x 2.4 inches (Length x height x width)',
        intro: "The Vertical Tote offers men with contemporary tastes an innovative alternative to a briefcase. Crafted in elegant embossed Taiga leather, it features reinforced corners that recall Louis Vuitton's trunk-making heritage, heightened with a tone-on-tone metal LV signature. Sleek and slim but with plenty of room inside, it comes with a removable strap for easy shoulder or cross-body carry.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-vertical-tote--M30811_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-vertical-tote-taiga-leather-bags--M30811_PM1_Cropped%20worn%20view.png?wid=1240&hei=1240',
    },
];

export default products;
