const products = [
    {
        id: 'M30851',
        name: 'District PM',
        price: '$2,440.00',
        detail: '10.2 x 7.9 x 2.8 inches (Length x height x width)',
        intro: 'The new District PM messenger bag, with its modern rectangular silhouette and functional size, is a fantastic everyday bag. Fashioned from deep-dyed Taiga leather, it features a zipped back pocket and an adjustable strap, for shoulder or cross-body wear. The strap has a D-ring to hang keys or a wallet.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-district-pm--M30851_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-district-pm-taiga-leather-bags--M30851_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M81628',
        name: 'Slender Wallet',
        price: '$570.00',
        detail: '4.3 x 3.3 x 0.8 inches (Length x height x width)',
        intro: 'The Slender Wallet in embossed Taiga leather with an understated two-tone colorway is the perfect marriage of form and function. The simple design features eight inside card slots and a compartment for bills. Compact and slim, it fits easily into almost any pocket.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-slender-wallet--M81628_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-slender-wallet-taiga-leather-small-leather-goods--M81628_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AA580',
        name: 'Jet Pocket Blouson',
        price: '$3,200.00',
        detail: '98% Wool, 1% Polyamide, 1% Elastane',
        intro: 'This contemporary twist on tailoring offers a chic blouson with crisp lines, piped pockets and a gathered bottom hem. It is made from wool-blend suiting fabric with a graphic jacquard Damier Cross motif. Sporty details, such as the pointed collar, the zip closure and elasticated bottom hem make this piece a versatile wardrobe addition.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-jet-pocket-blouson--HOFB1WMV6910_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-jet-pocket-blouson-ready-to-wear--HOFB1WMV6910_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1A9A8O',
        name: 'LV Flex Chelsea Boot',
        price: '$1,850.00',
        detail: 'Leather outsole with the Louis Vuitton ready-to-wear staple signature',
        intro: 'Crafted from the finest waxed calf leather, the LV Flex Chelsea boot features a prestigious Goodyear Flex construction: a traditional construction supplemented by an innovative cork filling in the sole for exceptional comfort. This model is finished with refined details, including Monogram-canvas trim at the back and Monogram Flowers on the heel.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-flex-chelsea-boot--BLHQ1YWC02_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-flex-chelsea-boot-shoes--BLHQ1YWC02_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M30859',
        name: 'Avenue Sling Bag',
        price: '$2,370.00',
        detail: '7.9 x 12.2 x 3.9 inches (length x Height x Width)',
        intro: "The Avenue Sling Bag in Taiga leather is an elegant option for those looking for a practical everyday bag. It features two zipped compartments to keep essentials organized and an extra-wide strap for shoulder wear that adjusts for left- or right-side carry. It's signed with metallic tone-on-tone LV initials.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-avenue-sling-bag--M30859_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-avenue-sling-bag-taiga-leather-bags--M30859_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AA57M',
        name: 'Single-Breasted Pont Neuf Cut-Away Jacket',
        price: '$3,200.00',
        detail: '100% Wool',
        intro: 'This single-breasted jacket is tailored in an elegant cut-away style, enhanced by the peak lapel, piped pockets and single slit at the back. It is constructed from wool suiting featuring a lustrous Monogram Geometric motif. This piece is fully lined with handwritten-effect Louis Vuitton signature fabric and finished with LV buttons.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-single-breasted-pont-neuf-cut-away-jacket--HOFJ6WMV1609_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-single-breasted-pont-neuf-cut-away-jacket-ready-to-wear--HOFJ6WMV1609_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AA7U6',
        name: 'Cigarette Pants',
        price: '$1,090.00',
        detail: '100% Wool',
        intro: 'These elegant cigarette pants are made from lustrous wool suiting fabric featuring a jacquard Monogram Chainette motif. They have a hook and bar closure on the front, two piped pockets with a horn button detail at the back, and an embroidered LV triangle tab at the waist. The pants are fully lined with a fabric featuring handwritten-effect Louis Vuitton signatures.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cigarette-pants--HOFP8WMU3631_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cigarette-pants-ready-to-wear--HOFP8WMU3631_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M45730',
        name: 'Duo Messenger',
        price: '$2,640.00',
        detail: '10.2 x 7.3 x 2 inches (length x Height x Width)',
        intro: "The Duo Messenger bag is a modern cross-body bag made from navy blue Monogram Shadow leather, with a a detachable coin purse on the strap. The leather's discreetly embossed Monogram pattern is amplified by the light blue Monogram print. The Duo in Monogram Shadow is for leather lovers looking for a subtle touch of color.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-duo-messenger--M45730_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-duo-messenger-monogram-shadow-bags--M45730_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M80422',
        name: 'Multiple Wallet',
        price: '$735.00',
        detail: '4.5 x 3.5 x 0.6 inches (length x Height x Width)',
        intro: 'The simple lines of the Multiple Wallet are perfectly complemented by the sober navy blue calf leather with a light blue Monogram pattern printed and embossed into the leather. The classic wallet design features a perfectly crafted interior with three card slots and two diagonal side slots for receipts.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-multiple-wallet--M80422_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-multiple-wallet-monogram-shadow-small-leather-goods--M80422_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M30856',
        name: 'Slim Briefcase',
        price: '$3,250.00',
        detail: '15.7 x 11.4 x 1.6 inches (length x Height x Width)',
        intro: 'Made from textured Taiga leather, the Slim Briefcase is an alternative to the classic business bag. The subtle hue of the leather and elegant details, such as the LV initials on the reinforced corners, bring style to this practical bag. It features an adjustable strap for comfortable shoulder carry and a compartment for a laptop.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-slim-briefcase--M30856_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-slim-briefcase-taiga-leather-bags--M30856_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Z1692W',
        name: 'LV Glide Sunglasses',
        price: '$475.00',
        detail: '14.8 x 5.1 cm/5.8 x 2 inches',
        intro: "The LV Glide Sunglasses are a timeless accessory available in a range of modern colour combinations. The shades feature a square shape and the House's iconic S-lock hinges, which are engraved with the LV initials. For added visual texture, certain pairs come with marbled frames.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-glide-sunglasses--Z1692W_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-glide-sunglasses-s00-sunglasses--Z1692W_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AA58P',
        name: 'Slim Long-Sleeved Shirt',
        price: '$820.00',
        detail: '100% Cotton',
        intro: 'This long-sleeved pure cotton shirt is tailored with an elegant slim fit. It features a subtle Monogram Chainette motif woven into the fabric, giving a tactile finish. The top button on the collar adds a final touch with LV stitching.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-slim-long-sleeved-shirt--HOS8PWMU5600_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-slim-long-sleeved-shirt-ready-to-wear--HOS8PWMU5600_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M77833',
        name: 'MNG Stripes Tie',
        price: '$220.00',
        detail: '58.3 x 3.1 inches (length x Height)',
        intro: 'The MNG Stripes Tie is a versatile piece from the Fall-Winter 2022 Collection. The design features diagonal stripes in contrasting colours that are decorated with a repeating pattern of Monogram motifs. A pure silk construction makes this accessory an elegant addition to any professional or evening look.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mng-stripes-tie--M77833_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-mng-stripes-tie-s00-new-this-season--M77833_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1A9A8V',
        name: 'LV Flex Derby',
        price: '$1,600.00',
        detail: 'Leather outsole with the Louis Vuitton ready-to-wear staple signature',
        intro: 'The LV Flex derby is crafted from a single piece of exceptionally supple waxed calf leather. This model features a Goodyear Flex construction: a traditional, high-end construction combined with an innovative cork filling in the sole for ultimate comfort. Refined details, including leather laces, a Monogram-canvas insert at the back, and Monogram Flowers on the heel, complete this design.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-flex-derby--BLHA1YWC02_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-flex-derby-shoes--BLHA1YWC02_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M30850',
        name: 'District PM',
        price: '$2,440.00',
        detail: '10.2 x 7.9 x 2.8 inches (length x Height x Width)',
        intro: 'The new District PM messenger bag, with its modern rectangular silhouette and functional size, is a fantastic everyday bag. Fashioned from deep-dyed Taiga leather, it features a zipped back pocket and an adjustable strap, for shoulder or cross-body wear. The strap has a D-ring to hang keys or a wallet.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-district-pm--M30850_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-district-pm-taiga-leather-bags--M30850_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M59255',
        name: 'City Keepall',
        price: '$2,590.00',
        detail: '10.6 x 6.7 x 5.1 inches (length x Height x Width)',
        intro: "This version of the iconic City Keepall in deep black Aerogram leather joins Louis Vuitton's New Classics line for Fall 2021. Fine-grained calfskin as soft and supple as an old-fashioned aerogram is accented with the LV initials in black metal for an understated signature touch. Easy to carry with its removable strap, it combines functionality with contemporary elegance.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-city-keepall--M59255_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-city-keepall-lv-aerogram-bags--M59255_PM1_Cropped%20worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82372',
        name: 'Pocket Organizer',
        price: '$595.00',
        detail: '3 x 4.4 x 0.4 inches (length x Height x Width)',
        intro: 'Fashioned from ultra-supple calf leather, the Pocket Organizer is adorned with a florescent two-tone version on the Monogram, with the LVs and Monogram Flowers almost seeming to glow. Three card slots and five pockets make this compact-sized wallet surprisingly practical.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer--M82372_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer-other-leathers-small-leather-goods--M82372_PM2_Front%20view.png?wid=1240&hei=1240',
    },

    {
        id: 'M82297',
        name: 'Multiple Wallet',
        price: '$820.00',
        detail: '4.5 x 3.5 x 0.6 inches (length x Height x Width)',
        intro: 'The Multiple Wallet is fashioned from extra-supple and smooth calfskin adorned with the Monogram Spotlight print. The Monogram Flowers and LVs seem to emit vivid neon echoes of themselves. Functional and sophisticated, the Multiple slips easily into most pockets.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-multiple-wallet--M82297_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-multiple-wallet-other-leathers-small-leather-goods--M82297_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M81967',
        name: 'LV x YK Slender Wallet',
        price: '$650.00',
        detail: '4.3 x 3.3 x 0.8 inches (length x Height x Width)',
        intro: 'Slim and practical, the LVxYK Slender Wallet gets an eye-catching graphic update for the new Louis Vuitton x Yayoi Kusama collection. Crafted in Monogram Eclipse Reverse canvas, it features a print of brightly colored pumpkins – a recurring theme in the venerated Japanese artist’s work, symbolizing warmth and upbeat optimism. A creative variation on a classic wallet, and an original gift for art lovers.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-slender-wallet--M81967_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-slender-wallet-monogram-eclipse-canvas-small-leather-goods--M81967_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M81972',
        name: 'LV x YK Gaston Wearable Wallet',
        price: '$2,290.00',
        detail: '8.7 x 5.7 x 1.8 inches (length x Height x Width)',
        intro: 'On-trend and practical, the LVxYK Gaston wearable wallet joins the “Pumpkins” theme of the Louis Vuitton x Yayoi Kusama collection with a vibrant new look. The venerated Japanese artist’s iconic pumpkins are printed in bright colors on Monogram Eclipse Reverse canvas. And it comes with a removable pumpkin-shaped pouch, perfect for coins and contactless payment cards.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-gaston-wearable-wallet--M81972_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-gaston-wearable-wallet-monogram-eclipse-canvas-bags--M81972_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M81969',
        name: 'LV x YK Pocket Organizer',
        price: '$580.00',
        detail: '3 x 4.4 x 0.4 inches (length x Height x Width)',
        intro: 'For the new Louis Vuitton x Yayoi Kusama collection, the LVxYK Pocket Organizer offers a spirited graphic update of a classic accessory. Monogram Eclipse Reverse canvas is adorned with brightly colored pumpkins, echoing an emblematic theme in the acclaimed Japanese artist’s work. For Kusama, pumpkins are a symbol of warmth and reassurance. Here they add an artistic accent to a handsome, practical wallet.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-pocket-organizer--M81969_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-pocket-organizer-monogram-eclipse-canvas-small-leather-goods--M81969_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82087',
        name: 'LV x YK Multiple Wallet',
        price: '$1,230.00',
        detail: '4.5 x 3.5 x 0.6 inches (length x Height x Width)',
        intro: 'The LVxYK Multiple wallet joins the “Faces” theme of the exceptional new Louis Vuitton x Yayoi Kusama collection. Cool blue Taurillon Monogram cowhide is adorned with appliqués in a rainbow of dazzling colors. Selected from “My Eternal Soul,” a series of paintings that the renowned Japanese artist initiated in 2009, the surrealistic images express joy and childlike enthusiasm, giving this functional wallet an infusion of artistic energy.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-multiple-wallet--M82087_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-multiple-wallet-taurillon-monogram-small-leather-goods--M82087_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M30949',
        name: 'Pocket Organizer',
        price: '$450.00',
        detail: '3 x 4.4 x 0.4 inches (length x Height x Width)',
        intro: 'The handsome and functional Pocket Organizer wallet looks fresh in Monogram canvas paired with matching colored Taiga cowhide leather. It has numerous card slots and pockets and yet slips easily into almost any pocket.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer--M30949_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer-taigarama-small-leather-goods--M30949_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M30893',
        name: 'Pocket Organizer',
        price: '$450.00',
        detail: '3 x 4.4 x 0.4 inches (length x Height x Width)',
        intro: 'The handsome and functional Pocket Organizer wallet looks fresh in Monogram canvas paired with matching colored Taiga cowhide leather. It has numerous card slots and pockets and yet slips easily into almost any pocket.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer--M30893_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer-taigarama-small-leather-goods--M30893_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M30933',
        name: 'Pocket Organizer',
        price: '$450.00',
        detail: '3 x 4.4 x 0.4 inches (length x Height x Width)',
        intro: 'The handsome and functional Pocket Organizer wallet looks fresh in Monogram canvas paired with matching colored Taiga cowhide leather. It has numerous card slots and pockets and yet slips easily into almost any pocket.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer--M30933_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer-taigarama-small-leather-goods--M30933_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82034',
        name: 'Pocket Organizer',
        price: '$495.00',
        detail: '3 x 4.4 x 0.4 inches (length x Height x Width)',
        intro: "This Pocket Organizer is crafted from Monogram Playground canvas. The playfully vibrant Monogram colorway is inspired by the playground created for the Show Spring-Summer 2023 show at the Carré du Louvres. Pocket-sized, this compact wallet's well-designed interior has three card slots and five inside pockets.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer--M82034_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pocket-organizer-monogram-other-small-leather-goods--M82034_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82005',
        name: 'Zippy Vertical Wallet',
        price: '$1,000.00',
        detail: '3.9 x 7.9 x 0.8 inches (length x Height x Width)',
        intro: 'With its bold bright colorway, Monogram Playground coated canvas brings a modern feel to the Zippy Vertical Wallet. As does the matching reinforced leather corner. Twelve card slots and a zipped pocket for coins, and a large gusseted compartment, make it highly practical.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-zippy-vertical-wallet--M82005_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-zippy-vertical-wallet-monogram-other-small-leather-goods--M82005_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82007',
        name: 'Vertical Trunk Wearable Wallet',
        price: '$3,000.00',
        detail: '4.2 x 6.9 x 2.7 inches (length x Height x Width)',
        intro: "Fashioned from Monogram Playground canvas, the Vertical Trunk Wearable Wallet is inspired by the traditional trunk and includes details like the S-Lock, reinforced corners, and rivets. Convenient, it’s the perfect size for daily essentials and can hold two smartphones, a pocket organizer, and other smaller items. The magnetic flap offers easy access what's inside.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-vertical-trunk-wearable-wallet--M82007_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-vertical-trunk-wearable-wallet-monogram-other-bags--M82007_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M30897',
        name: 'Multiple Wallet',
        price: '$560.00',
        detail: '4.5 x 3.5 x 0.6 inches (length x Height x Width)',
        intro: "One of the House's iconic men's wallets, the Multiple Wallet looks superb in the materials of the Taigarama line: Monogram canvas paired with Taiga cowhide leather. Practical and elegant, the Multiple fits comfortably into most pockets.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-multiple-wallet--M30897_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-multiple-wallet-taigarama-small-leather-goods--M30897_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABNRV',
        name: 'Suede Overshirt',
        price: '$4,700.00',
        detail: 'Embossed Monogram on collar, pocket and cuffs',
        intro: 'This versatile overshirt in light certified suede has a casual yet elegant mood. The relaxed fit is distinguished with an allover Monogram on the cuffs, collar and the left chest pocket, while engraved Staples on the sleeves add a discreet signature. The refined sandy tones complement the desert-inspired pieces of this collection.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-suede-overshirt--HPL40EZA0815_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-suede-overshirt-ready-to-wear--HPL40EZA0815_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABJJZ',
        name: 'Monogram Silk Short',
        price: '$1,570.00',
        detail: 'Monogram Sand print allover',
        intro: 'These refined silk shorts with a comfortable drawstring waist move effortlessly from day to night. The dark blue fabric is embellished with this collection’s Monogram Sand motif inspired by the desert, evoking wind-swept dunes for a graphic effect. This piece can be paired with a matching shirt for an elegant ensemble.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-silk-short--HPP34WZ49920_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-silk-short-ready-to-wear--HPP34WZ49920_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
];

export default products;
