const products = [
    {
        id: 'Q9F15A',
        name: 'Idylle Blossom ring, 3 golds and diamonds',
        price: '$4,000.00',
        detail: 'Yellow, white and pink gold (18kt) and diamonds',
        intro: 'To reserve online today and experience in store tomorrow, select “Collect in Store” at checkout. Feminine and playful, the Idylle Blossom collection brings life to the Monogram flowers, created in 1896 by Georges-Louis Vuitton. Blooming in white, pink or yellow golds, the 3 exquisite flowers are joyfully combined in a personal precious bouquet, lighting up the silhouette with dancing sparkles. Idylle Blossom creations reveal the free-spirited Louis Vuitton woman attitude.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ring-3-golds-and-diamonds--Q9F15A_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ring-3-golds-and-diamonds-categories--Q9F15A_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q06174',
        name: 'Idylle Blossom Ear Cuff, Pink Gold And Diamonds - Per Unit',
        price: '$3,550.00',
        detail: 'Pink Gold (18 kt)',
        intro: 'Fashioned from 18-karat pink gold, the Idylle Blossom ear cuff is an homage to the Monogram Flower. On three bands of pink gold the flower sits, eight brilliant-cut diamonds balancing on four petals. Worn alone or combined with studs or hoops, this piece lends itself to a variety of stylings.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ear-cuff-pink-gold-and-diamonds-per-unit--Q06174_PM2_Front%20View.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ear-cuff-pink-gold-and-diamonds-per-unit-categories--Q06174_PM1_Other%20view2.png?wid=1240&hei=1240',
    },
    {
        id: 'Q06169',
        name: 'Idylle Blossom Ear Stud, Pink Gold And Diamonds - Per Unit',
        price: '$2,710.00',
        detail: 'Pink gold (18 kt)',
        intro: 'Both the stud and the hanging Monogram Flower are covered with diamonds on this Idylle Blossom earring. Made from 18-karat pink gold, the design celebrates the iconic Monogram Flower, created in 1896 by Georges-Louis Vuitton. This elegant piece will complement any silhouette, whether for day or evening.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ear-stud-pink-gold-and-diamonds-per-unit--Q06169_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ear-stud-pink-gold-and-diamonds-per-unit-categories--Q06169_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q94329',
        name: 'IDYLLE BLOSSOM Y PENDANT, 3 GOLDS AND DIAMONDS',
        price: '$5,050.00',
        detail: 'Yellow, white and pink gold (18 kt) and diamonds',
        intro: 'Feminine and playful, the Idylle Blossom collection brings life to the Monogram flowers, created in 1896 by Georges-Louis Vuitton. Blooming in white, pink or yellow golds, the 3 exquisite flowers are joyfully combined in a personal precious bouquet, lighting up the silhouette with dancing sparkles. Idylle Blossom creations reveal the free-spirited Louis Vuitton woman attitude.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-y-pendant-3-golds-and-diamonds--Q94329_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-y-pendant-3-golds-and-diamonds-categories--Q94329_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q95532',
        name: 'Idylle Blossom Twist Bracelet, Pink Gold',
        price: '$3,750.00',
        detail: 'Pink gold (18kt) and diamond',
        intro: 'Identifiable, feminine and playful, the Idylle Blossom collection enlivens the Monogram flowers, created in 1896 by Georges-Louis Vuitton. These bracelets are totally “shape memory” owing to its incredible flexibility. Blooming in white, pink or yellow gold, the 3 exquisite flowers can be mixed in a personal precious bouquet or for wearing separately, lighting up the silhouette of trendy and confident Louis Vuitton women.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-twist-bracelet-pink-gold--Q95532_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-twist-bracelet-pink-gold-categories--Q95532_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q9R75D',
        name: 'Idylle Blossom Paved Ring, 3 Golds And Diamonds',
        price: '$7,600.00',
        detail: 'Yellow, white and pink gold (18 kt)',
        intro: "Playfully feminine, the Idylle Blossom paved ring brings life to the Monogram Flowers, created over a hundred years ago by Georges-Louis Vuitton. Cast from 18-karat white, pink, and yellow gold, the three blossoms are covered with more than 150 pavé diamonds. The precious stones are a sparkling celebration of the collection's tenth anniversary.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-paved-ring-3-golds-and-diamonds--Q9R75D_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-paved-ring-3-golds-and-diamonds-categories--Q9R75D_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q96836',
        name: 'Idylle Blossom Mono Chain Earrings, Pink Gold And Diamonds - Per Unit',
        price: '$5,300.00',
        detail: 'Pink Gold (18 kt)',
        intro: 'Cast from 18-karat pink gold, the Idylle Blossom Mono Chain earring adds an on-trend edge to any look. The Monogram Flower stud and ear clip, both encrusted with diamond pavé, are connected by a delicate chain embellished with two brilliant-cut stones for even more eye-catching sparkle. Easy to wear and pair with other jewels from the collection.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-mono-chain-earrings-pink-gold-and-diamonds-per-unit--Q96836_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-mono-chain-earrings-pink-gold-and-diamonds-per-unit-categories--Q96836_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q93710',
        name: 'Star Blossom Pendant, Pink Gold And Diamonds',
        price: '$5,000.00',
        detail: 'Pink Gold (18 kt)',
        intro: 'The Star Blossom collection brings the Monogram Flower -- designed in 1896 by G.-L. Vuitton -- to sparkling life. Pavé set with diamonds, this 18-carat pink-gold pendant is as radiant as the first light of day. A modern, feminine jewel, it is precious yet easy to wear with a variety of looks, from dressy to relaxed.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-star-blossom-pendant-pink-gold-and-diamonds--Q93710_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-star-blossom-pendant-pink-gold-and-diamonds-categories--Q93710_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q95813',
        name: 'Idylle Blossom Two-Row Bracelet, Pink Gold And Diamonds',
        price: '$17,700.00',
        detail: 'Pink Gold (18 kt)',
        intro: 'This Idylle Blossom bracelet is fashioned from 18-karat pink gold, fully paved with brilliant diamonds and set with a diamond-encrusted Monogram Flower. The double-row design looks chic and contemporary – like two bracelets stacked together. This sleek cuff combines stylishly with other jewels from the range, for a modern way to wear diamonds every day.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-two-row-bracelet-pink-gold-and-diamonds--Q95813_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-two-row-bracelet-pink-gold-and-diamonds-categories--Q95813_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q96835',
        name: 'Idylle Blossom Studs, 3 Golds And Diamonds',
        price: '$9,750.00',
        detail: 'White, Yellow and Pink Gold (18 kt)',
        intro: 'Made from white, yellow and pink 18-karat gold, these Idylle Blossom ear studs are composed of iconic Monogram Flower motifs, illuminated with diamond pavé and embellished with brilliants-cut diamonds. Styled solo, worn as a pair or mixed with other jewels from the collection, they add modern sparkle to any look, whether dressed-up or relaxed.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-studs-3-golds-and-diamonds--Q96835_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-studs-3-golds-and-diamonds-categories--Q96835_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q94191',
        name: 'Idylle Blossom sautoir, 3 golds and diamonds',
        price: '$11,900.00',
        detail: 'Yellow, white and pink gold (18kt) and diamonds',
        intro: 'Feminine and playful, the Idylle Blossom collection brings life to the Monogram flowers, created in 1896 by Georges-Louis Vuitton. Blooming in white, pink or yellow golds, the 3 exquisite flowers are joyfully combined in a personal precious bouquet, lighting up the silhouette with dancing sparkles. Idylle Blossom creations reveal the free-spirited Louis Vuitton woman attitude.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-sautoir-3-golds-and-diamonds--Q94191_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-sautoir-3-golds-and-diamonds-categories--Q94191_PM1_Ambiance%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q93612',
        name: 'Color Blossom BB Star Pendant, Pink gold, Pink Mother-of-Pearl and diamond',
        price: '$2,970.00',
        detail: 'Pink gold (18kt), Pink mother-of-pearl and diamond',
        intro: "Color Blossom BB celebrates the Monogram flowers, created in 1896 by Georges-Louis Vuitton. The flower blooms into a small format in carved pink mother-of-pearl and is set into pink gold highlighted by a diamond. Months of work were necessary to perfect the stone's subtle curves and sparkle.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-color-blossom-bb-star-pendant-pink-gold-pink-mother-of-pearl-and-diamond--Q93612_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-color-blossom-bb-star-pendant-pink-gold-pink-mother-of-pearl-and-diamond-categories--Q93612_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q96667',
        name: 'Color Blossom BB Star Ear Studs, Pink gold, pink Mother of pearl and diamonds',
        price: '$4,050.00',
        detail: 'Pink gold (18kt), Pink mother of pearl and diamonds',
        intro: "Color Blossom BB celebrates the Monogram flowers, created in 1896 by Georges-Louis Vuitton. In these 18-carat pink gold earrings, the flower blooms into carved pink mother-of-pearl and is highlighted by a diamond setting. Months of work were necessary to perfect the stone's subtle curves.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-color-blossom-bb-star-ear-studs-pink-gold-pink-mother-of-pearl-and-diamonds--Q96667_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-color-blossom-bb-star-ear-studs-pink-gold-pink-mother-of-pearl-and-diamonds-categories--Q96667_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q06172',
        name: 'Idylle Blossom Reversible Stud, Pink And Yellow Gold And Diamond - Per Unit',
        price: '$1,940.00',
        detail: 'Pink and yellow gold (18 kt)',
        intro: 'The Idylle Blossom reversible stud in 18-karat pink and yellow gold combines versatility with iconic Louis Vuitton style. The two-sided ear stud can be worn two ways: with the LV Initials outwards or featuring the classic Monogram Flower. The blossom is embellished with a shimmering diamond at its heart.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-reversible-stud-pink-and-yellow-gold-and-diamond-per-unit--Q06172_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-reversible-stud-pink-and-yellow-gold-and-diamond-per-unit-categories--Q06172_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q93871',
        name: 'Idylle Blossom Pendant, Pink Gold And Diamonds',
        price: '$3,800.00',
        detail: 'Pink gold (18 kt)',
        intro: "For the collection's 10th anniversary, this glittering version of the Idylle Blossom pendant is embellished with brilliant diamonds on the petals of its Monogram Flower. Fashioned from 18-karat pink gold, the blossom hangs from a delicate chain adorned with a diamond, bringing a feminine feel to this easy-to-match piece.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-pendant-pink-gold-and-diamonds--Q93871_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-pendant-pink-gold-and-diamonds-categories--Q93871_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q06168',
        name: 'Idylle Blossom Ear Stud, Yellow Gold And Diamonds - Per Unit',
        price: '$2,710.00',
        detail: 'Yellow gold (18 kt)',
        intro: "With diamonds on the tiny petals of the Monogram Flower, the Idylle Blossom ear stud takes on a joyful feel for the collection's tenth birthday. Cast from 18-karat yellow gold, the iconic floral design is inlaid with brilliantly faceted diamonds. Worn singly or matched with studs, hoops, necklaces or even bracelets, this piece lends itself to a myriad of stylings.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ear-stud-yellow-gold-and-diamonds-per-unit--Q06168_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ear-stud-yellow-gold-and-diamonds-per-unit-categories--Q06168_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q93870',
        name: 'Idylle Blossom Pendant, Yellow Gold And Diamonds',
        price: '$3,800.00',
        detail: 'Yellow gold (18 kt)',
        intro: 'Cast from 18-karat yellow gold, the Idylle Blossom pendant features the iconic Monogram Flower encrusted with diamond pavé that shimmers and shines in the light. The delicate chain is embellished with a brilliant-cut stone for even more eye-catching glimmer. Playfully feminine, this pendant can be mixed and matched with any other piece from the collection.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-pendant-yellow-gold-and-diamonds--Q93870_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-pendant-yellow-gold-and-diamonds-categories--Q93870_PM1_Ambiance%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q95713',
        name: 'Idylle Blossom Twist Bracelet, Yellow Gold And Diamonds',
        price: '$7,750.00',
        detail: 'Yellow Gold, 18 kt',
        intro: 'The Idylle Blossom Twist bracelet in 18-karat yellow gold sparkles alluringly with pavé diamonds, set in a manner that magnifies their brilliance. Instantly recognizable with its Monogram Flower motif, designed by Georges-Louis Vuitton in 1896, this incredibly flexible bangle adds playful panache to any look, worn alone or stacked with others on the wrist.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-twist-bracelet-yellow-gold-and-diamonds--Q95713_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-twist-bracelet-yellow-gold-and-diamonds-categories--Q95713_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q93280',
        name: 'Idylle Blossom pendant, yellow gold and diamond',
        price: '$2,490.00',
        detail: 'Yellow gold (18kt) and diamond',
        intro: 'Feminine and playful, the Idylle Blossom collection brings life to the Monogram flowers, created in 1896 by Georges-Louis Vuitton. Blooming in white, pink or yellow golds, the 3 exquisite flowers are joyfully combined in a personal precious bouquet, lighting up the silhouette with dancing sparkles. Idylle Blossom creations reveal the free-spirited Louis Vuitton woman attitude.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-pendant-yellow-gold-and-diamond--Q93280_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-pendant-yellow-gold-and-diamond-categories--Q93280_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q95588',
        name: 'IDYLLE BLOSSOM MONOGRAM BRACELET, YELLOW GOLD AND DIAMONDS',
        price: '$7,350.00',
        detail: 'Yellow gold (18 kt) and diamonds',
        intro: 'The two iconic LV initials meet the Idylle Blossom flowers to recreate the legendary Monogram canvas. Identifiable, feminine and playful, the collection enlivens the Monogram flowers, created in 1896 by Georges-Louis Vuitton. Idylle Blossom creations reveal the free-spirited Louis Vuitton woman attitude.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-monogram-bracelet-yellow-gold-and-diamonds--Q95588_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-monogram-bracelet-yellow-gold-and-diamonds-categories--Q95588_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q06171',
        name: 'Idylle Blossom Reversible Stud, Yellow And White Gold And Diamond - Per Unit',
        price: '$2,190.00',
        detail: 'Yellow and white gold (18 kt)',
        intro: 'The Idylle Blossom reversible stud can be worn two ways, both stunning. One side features the LV Initials in 18-karat white gold while the other is a Monogram Flower in 18-karat yellow gold with a diamond at its center. The contrasting golds and bold shapes make it striking no matter which side is chosen.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-reversible-stud-yellow-and-white-gold-and-diamond-per-unit--Q06171_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-reversible-stud-yellow-and-white-gold-and-diamond-per-unit-categories--Q06171_PM1_Other%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q95443',
        name: 'Idylle Blossom XL Bracelet, 3 golds and diamonds',
        price: '$5,800.00',
        detail: 'Yellow, white & pink gold (18kt)',
        intro: 'Feminine and playful, the Idylle Blossom collection celebrates the Monogram flowers, created in 1896 by Georges-Louis Vuitton. Blooming in white, pink and yellow gold, the 3 exquisite flowers are joyfully combined in a personal precious bouquet, lighting up the silhouette with dancing sparkles. Idylle Blossom creations reveal the free-spirited Louis Vuitton woman attitude.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-xl-bracelet-3-golds-and-diamonds--Q95443_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-xl-bracelet-3-golds-and-diamonds-categories--Q95443_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q06177',
        name: 'Idylle Blossom Small Hoop, White Gold And Diamond - Per Unit',
        price: '$2,060.00',
        detail: 'White gold (18 kt)',
        intro: 'This Idylle Blossom small hoop earring brings the understated elegance of 18-karat white gold to the Monogram Flower, created in 1896 by Georges-Louis Vuitton. Within its perfect tiny circle sits the delicate blossom, a glittering diamond at its center. Perfect styled alone or matched with other pieces from the collection for a personalized look.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-small-hoop-white-gold-and-diamond-per-unit--Q06177_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-small-hoop-white-gold-and-diamond-per-unit-categories--Q06177_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q95694',
        name: 'Idylle Blossom Twist Bracelet, White Gold And Diamonds',
        price: '$8,250.00',
        detail: 'White Gold, 18 kt',
        intro: 'The Idylle Blossom Twist bracelet in 18-karat white gold is luxuriously set with pavé diamonds in a manner that enhances their sparkle. Instantly recognizable with its sun-motif Monogram Flower, designed by Georges-Louis Vuitton in 1896, this incredibly flexible bangle looks trendy and playful, worn alone or stacked with others on the wrist.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-twist-bracelet-white-gold-and-diamonds--Q95694_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-twist-bracelet-white-gold-and-diamonds-categories--Q95694_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q06173',
        name: 'Idylle Blossom Mono Chain Earring, White Gold And Diamonds - Per Unit',
        price: '$5,550.00',
        detail: 'White Gold (18 kt)',
        intro: 'Cast from 18-karat white gold, the Idylle Blossom mono chain earring shimmers with diamond pavé. The Monogram Flower stud and ear clip, both encrusted with diamonds, are connected by a delicate chain, itself embellished with two brilliant-cut stones. Easy to wear and pair with other jewels from the collection.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-mono-chain-earring-white-gold-and-diamonds-per-unit--Q06173_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-mono-chain-earring-white-gold-and-diamonds-per-unit-categories--Q06173_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q95589',
        name: 'IDYLLE BLOSSOM MONOGRAM BRACELET, WHITE GOLD AND DIAMONDS',
        price: '$7,900.00',
        detail: 'White gold (18 kt) and diamonds',
        intro: 'The two iconic LV initials meet the Idylle Blossom flowers to recreate the legendary Monogram canvas. Identifiable, feminine and playful, the collection enlivens the Monogram flowers, created in 1896 by Georges-Louis Vuitton. Idylle Blossom creations reveal the free-spirited Louis Vuitton woman attitude.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-monogram-bracelet-white-gold-and-diamonds--Q95589_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-monogram-bracelet-white-gold-and-diamonds-categories--Q95589_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q06170',
        name: 'Idylle Blossom Ear Stud, White Gold And Diamonds - Per Unit',
        price: '$2,970.00',
        detail: 'White gold (18 kt)',
        intro: "The Idylle Blossom ear stud celebrates the Monogram Flower, introduced in 1896 by Georges-Louis Vuitton. Cast in 18-karat white gold and adorned with diamonds, it's exquisitely understated. The simple yet iconic shape, a flower within a circle, sparkles. It can be matched with other studs, hoops, necklaces or even bracelets from the collection for a layered Monogram look.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ear-stud-white-gold-and-diamonds-per-unit--Q06170_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-ear-stud-white-gold-and-diamonds-per-unit-categories--Q06170_PM1_Other%20view2.png?wid=1240&hei=1240',
    },
    {
        id: 'Q93764',
        name: 'Idylle Blossom Medallion, White Gold And Diamonds',
        price: '$15,900.00',
        detail: 'White Gold (18 kt)',
        intro: 'The Idylle Blossom collection pays tribute to the Monogram Flower, with modern pieces like this medallion necklace, cast from 18-karat white gold and illuminated with brilliant diamond pavé. With an adjustable chain that allows for different stylings, this elegant yet playful jewel can be worn alone or layered with other models from the Idylle Blossom line.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-medallion-white-gold-and-diamonds--Q93764_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-medallion-white-gold-and-diamonds-categories--Q93764_PM1_Ambiance%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q93872',
        name: 'Idylle Blossom Pendant, White Gold And Diamonds',
        price: '$4,050.00',
        detail: 'White gold (18 kt)',
        intro: 'To celebrate the 10th anniversary of the Idylle Blossom Collection, the Monogram Flower on this pendant in 18-karat white gold is encrusted with diamonds. Playfully feminine, this pendant can be mixed and matched with any other piece from the collection.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-pendant-white-gold-and-diamonds--Q93872_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-idylle-blossom-pendant-white-gold-and-diamonds-categories--Q93872_PM1_Ambiance%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q95879',
        name: 'B Blossom Open Bangle, Yellow Gold, White Gold, Malachite And Diamonds',
        price: '$8,000.00',
        detail: 'Yellow and White Gold (18kt)',
        intro: 'Cast from 18-karat gold, the sleek B Blossom bangle bracelet features a modern, open-band shape. The polished green malachite gemstone is centered with a Monogram Flower motif composed of four superbly cut diamonds. Worn alone, coupled with a B Blossom cuff or stacked with other bracelets, this signature piece lends sparkle and style to any silhouette.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-b-blossom-open-bangle-yellow-gold-white-gold-malachite-and-diamonds--Q95879_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-b-blossom-open-bangle-yellow-gold-white-gold-malachite-and-diamonds-categories--Q95879_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q96948',
        name: 'B Blossom Earrings, Yellow Gold, White Gold, Malachite And Diamonds',
        price: '$8,000.00',
        detail: 'Yellow and White Gold (18kt)',
        intro: 'These B Blossom earrings are meticulously crafted from 18-karat yellow gold and set with rounded, polished green malachite drops. The gemstones are inlaid with the iconic Monogram Flower motif, composed of brilliantly faceted diamonds. With their modern design and alluring hue, these jewels will enhance any silhouette, from casual-chic to elegant eveningwear.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-b-blossom-earrings-yellow-gold-white-gold-malachite-and-diamonds--Q96948_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-b-blossom-earrings-yellow-gold-white-gold-malachite-and-diamonds-categories--Q96948_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Q9N92A',
        name: 'B Blossom Ring, Yellow Gold, White Gold, Cornelian And Diamonds',
        price: '$4,150.00',
        detail: 'Yellow and White Gold (18 kt)',
        intro: 'From the B Blossom collection, a suite of bold, modern jewels, comes this 18-karat yellow-gold ring, set with a red-hued cornelian. Inlaid with four diamonds in a Monogram Flower motif, the rounded, polished gemstone recalls a signature stamp. Styled solo or stacked in pairs or threes, it is sure to please a woman who always makes her mark.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-b-blossom-ring-yellow-gold-white-gold-cornelian-and-diamonds--Q9N92A_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-b-blossom-ring-yellow-gold-white-gold-cornelian-and-diamonds-categories--Q9N92A_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
];

export default products;
