const products = [
    {
        id: 'M82168',
        name: 'Micro Vanity',
        price: '$1,900.00',
        detail: '4.3 x 3.9 x 3.1 inches (length x Height x Width)',
        intro: "The Micro Vanity is a tiny, wearable accessory that draws inspiration from Louis Vuitton's travel heritage and iconic vanity cases. It is crafted from grained Monogram Empreinte leather with a shimmering, pearly finish and features a removable, adjustable chain with an LV Circle charm. This sweet, miniature bag offers space for small essentials, as well as a removable mirror for touching up on the go.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-micro-vanity--M82168_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-micro-vanity-monogram-empreinte-leather-small-leather-goods--M82168_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82193',
        name: 'Micro Vanity',
        price: '$1,900.00',
        detail: '4.3 x 3.9 x 3.1 inches (length x Height x Width)',
        intro: "The Micro Vanity is a tiny, wearable accessory that draws inspiration from Louis Vuitton's travel heritage and iconic vanity cases. It is crafted from grained Monogram Empreinte leather with a shimmering, pearly finish and features a removable, adjustable chain with an LV Circle charm. This sweet, miniature bag offers space for small essentials, as well as a removable mirror for touching up on the go.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-micro-vanity--M82193_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-micro-vanity-monogram-empreinte-leather-small-leather-goods--M82193_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82343',
        name: 'Victorine Wallet',
        price: '$840.00',
        detail: '4.7 x 3.7 x 0.6 inches (length x Height x Width)',
        intro: "To celebrate Mother's Day, the Victorine wallet is revisited in Monogram Empreinte leather with a beautiful pearly shimmer and embellished with a feminine Monogram flower as press stud. A perfect gift, this tiny wallet unfolds to reveal a surprisingly spacious interior, with several pockets and six card slots. Its envelope-style flap is sealed with a gold-tone press-stud in the shape of a Monogram Flower.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-victorine-wallet--M82343_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-victorine-wallet-monogram-empreinte-leather-small-leather-goods--M82343_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82171',
        name: 'LV Charms Card Holder',
        price: '$445.00',
        detail: '4 x 2.9 x 0.1 inches (length x Height x Width)',
        intro: "This special Mother's Day edition of the LV Charms Card Holder makes a perfect gift. It comes in grained Monogram Empreinte leather with a shimmering, pearly finish and is embellished with two Monogram Flower charms. It offers five slots for credit, travel or business cards: two slots on each side and a larger one in the middle.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-charms-card-holder--M82171_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-charms-card-holder-monogram-empreinte-leather-small-leather-goods--M82171_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82352',
        name: 'Card Holder',
        price: '$300.00',
        detail: '4.3 x 2.8 x 0.2 inches (length x Height x Width)',
        intro: "This special edition of the Card Holder comes in Louis Vuitton's emblematic Epi leather, recognizable for its distinctive grain. Combining elegance with practicality, this accessory offers three card slots: one on each side and a larger slot in the middle. It is discreetly embossed with the LV Initials signature.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-card-holder--M82352_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-card-holder-epi-leather-small-leather-goods--M82352_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82174',
        name: 'Sarah Wallet',
        price: '$1,070.00',
        detail: '7.5 x 4.1 x 0.8 inches (length x Height x Width)',
        intro: "This special edition of the classic Sarah wallet is a perfect gift for Mother's Day. Grained Monogram Empreinte leather with a shimmering, pearly finish complements this elegant model, whose envelope-style flap is sealed with a press-stud in the shape of a Monogram Flower. Inside, this wallet offers multiple pockets, compartments and card slots.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-sarah-wallet--M82174_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-sarah-wallet-monogram-empreinte-leather-small-leather-goods--M82174_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82173',
        name: 'Clémence Wallet',
        price: '$905.00',
        detail: '7.9 x 3.5 x 0.8 inches (length x Height x Width)',
        intro: "To celebrate Mother's Day, the elegant Clémence wallet is revisited in supple, grained Monogram Empreinte leather with a beautiful pearly shimmer. Further enhancing this feminine design, the gold-tone zip pull takes the shape of a Monogram Flower. A thoughtful gift, this slim-line wallet unzips to reveal a well-designed interior with multiple practical features.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cl%C3%A9mence-wallet--M82173_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cl%C3%A9mence-wallet-monogram-empreinte-leather-small-leather-goods--M82173_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82342',
        name: 'Nano Speedy',
        price: '$1,900.00',
        detail: '6.3 x 3.9 x 3 inches (length x Height x Width)',
        intro: "This special Mother's Day edition of the Nano Speedy bag comes in grained, embossed Monogram Empreinte leather with a beautiful pearly shimmer. This miniature replica of the iconic Speedy comes with two handles and a removable, adjustable strap offering different carry options. Monogram Flower details in silver-tone metal further enhance this feminine piece.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-nano-speedy--M82342_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-nano-speedy-monogram-empreinte-leather-small-leather-goods--M82342_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46581',
        name: 'Néonoé BB',
        price: '$1,900.00',
        detail: '7.9 x 7.9 x 5.1 inches (length x Height x Width)',
        intro: "The NéoNoé BB in Monogram canvas with natural leather trim is a smaller interpretation of the House's iconic NéoNoé bucket bag. Spacious enough to hold essentials such as keys, Airpods, and an iPhone, it features a leather drawstring to close the bag and keep belongings secure. A removable handle and detachable, adjustable strap offer multiple carry options.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-n%C3%A9ono%C3%A9-bb--M46581_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-n%C3%A9ono%C3%A9-bb-monogram-handbags--M46581_PM1_Closeup%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46055',
        name: 'Cluny Mini',
        price: '$2,280.00',
        detail: '7.9 x 6.3 x 3 inches (length x Height x Width)',
        intro: 'The adorable Cluny Mini handbag in iconic Monogram canvas is designed to delight LV lovers. A perfect little bag for daily wear, it features a signature Toron handle and key bell in the Maison’s classic natural leather. A textile strap enriched with a woven "Louis Vuitton" can be added or detached, thus enhancing the bag\'s versatility.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cluny-mini--M46055_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cluny-mini-monogram-handbags--M46055_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABIVA',
        name: 'Run Away Sneaker',
        price: '$1,210.00',
        detail: 'Hidden footbed (2 cm / 0.8 inches)',
        intro: 'Monogram denim canvas is teamed with plain and metallic leather on this summery version of the cult Run Away sneaker. This design is notable for its wedge-shaped outsole and rich detailing, including a gold-tone stabilizer engraved with the LV Circle logo, which also features in rubber on the side. A hidden footbed discreetly adds extra height.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-run-away-sneaker--AP9U2ADN31_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-run-away-sneaker-shoes--AP9U2ADN31_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M7093S',
        name: 'Beachview Bucket Hat',
        price: '$760.00',
        detail: '10.6 x 5.9 x 10.6 inches (length x Height x Width)',
        intro: 'The new Beachview Bucket Hat provides stylish protection for the head and hair on sunny summer days. Outsized Monogram Flowers adorn natural raffia-look fabric enhanced by natural cowhide piping around the brim. Easy to pack for a beach holiday, it features an LV logo on the crown for an extra signature touch.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-beachview-bucket-hat--M7093S_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-beachview-bucket-hat-s00-hats-and-gloves--M7093S_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABJO8',
        name: 'Nautical Knots Pajama Shorts',
        price: '$1,310.00',
        detail: 'Main Material : 100% Silk',
        intro: "These chic pajama shorts are cut in a clean, casual shape from breezy silk crepe de chine for a laidback loungey look, trimmed with an effortless elasticated waistband. Complete with an allover print of this season's elegant nautical knots motif for a summery seaside feel.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-nautical-knots-pajama-shorts--FPPA26ZS9001_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-nautical-knots-pajama-shorts-ready-to-wear--FPPA26ZS9001_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M0710Y',
        name: 'LV Edge 25mm Reversible Belt',
        price: '$690.00',
        detail: '27.6 x 9.8 inches (length x Width)',
        intro: "The new LV Edge buckle draws inspiration from the Coussin handbag's chain. Its gold-colored links are engraved with the LV initials and Monogram Flowers for a sophisticated signature detail. Reversible, offering a choice of Monogram canvas or taupe calfskin, this belt goes perfectly with everyday or more formal looks.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-edge-25mm-reversible-belt--M0710Y_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-edge-25mm-reversible-belt-monogram-belts--M0710Y_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M1052A',
        name: 'LV Crown Bracelet',
        price: '$1,020.00',
        detail: 'Lock width: ~ 1.2 inches/3 cm',
        intro: "New for Spring-Summer 2023, the LV Crown bracelet exemplifies the House's timeless heritage of expert craftsmanship. The chunky brass chain links are adorned with Monogram Flowers for a creative signature touch, complemented by the LV initials on the clasp. A striking addition to a stylish outfit, it can be matched with the LV Crown necklace or earrings.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-crown-bracelet--M1052A_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-crown-bracelet-s00-fashion-jewelry--M1052A_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M01272',
        name: 'LV Crown Earrings',
        price: '$665.00',
        detail: 'Length: ~ 1.1 inches/2.8 cm',
        intro: "The LV Crown earrings perpetuate the tradition of craftsmanship and innovation that has become the House's hallmark. The perfectly uniform placement of the Monogram Flowers adorning the edges recalls the rivets studding Louis Vuitton's historic trunks. Crafted in brass with a lustrous gold-tone finish, they can be worn with everyday or more formal looks.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-crown-earrings--M01272_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-crown-earrings-s00-fashion-jewelry--M01272_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABHQV',
        name: 'Run 55 Sneaker',
        price: '$1,270.00',
        detail: 'Louis Vuitton signature, LV Initials and Monogram Flowers on the back',
        intro: 'The Run 55 sneaker is reinterpreted this season in a summery version in Monogram denim canvas. Its elaborately constructed upper also features lycra, calf leather and metallic lambskin, notably on the gold-tone spoiler at the back. This model is characterized by its numerous signatures and its lifted rubber outsole, which provides optimum comfort.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-run-55-sneaker--AP4U2ADN31_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-run-55-sneaker-shoes--AP4U2ADN31_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82210',
        name: 'Wallet on Chain Ivy',
        price: '$1,900.00',
        detail: '9.3 x 4.7 x 1.7 inches (length x Height x Width)',
        intro: 'The on-trend Wallet on Chain Ivy is made from grained Monogram Empreinte leather, embossed with an oversized Monogram motif. The perfect day-to-evening companion, it can be carried as a clutch, worn close to the shoulder with its short gold-color chain, or for a more casual attitude, carried cross-body thanks to its removable and adjustable leather strap.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-wallet-on-chain-ivy--M82210_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-wallet-on-chain-ivy-monogram-empreinte-leather-small-leather-goods--M82210_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46585',
        name: 'Trianon PM',
        price: '$3,150.00',
        detail: '11 x 7.1 x 3.1 inches (length x Height x Width)',
        intro: 'The Trianon PM tote, with its distinctive V-cut silhouette, is made from grained Monogram Empreinte leather with the Monogram Flowers and LVs embossed then printed on the leather in a soft cream tone. A long adjustable and removable strap, in addition to the two top handles, give carry options.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm--M46585_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm-monogram-empreinte-leather-handbags--M46585_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABIGN',
        name: 'Dita Sandal',
        price: '$1,210.00',
        detail: '6.5 cm / 2.6-inch heel covered with metallic calf leather',
        intro: 'The Dita sandal contrasts the velvety texture of suede baby goat leather with shiny, gold-tone details: a precious LV Initials chain inspired by the jewelry collection and metallic calfskin on the heel. The upper is distinguished by its slender straps, which are complemented by a flared block heel. A fine leather outsole completes this elegant, feminine design.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-dita-sandal--APQS1FSU02_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-dita-sandal-shoes--APQS1FSU02_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABCIT',
        name: 'Inverted Mahina Monogram Pajama Shirt ',
        price: '$1,950.00',
        detail: 'Main Material : 100% Silk',
        intro: 'The Dita sandal contrasts the velvety texture of suede baby goat leather with shiny, gold-tone details: a precious LV Initials chain inspired by the jewelry collection and metallic calfskin on the heel. The upper is distinguished by its slender straps, which are complemented by a flared block heel. A fine leather outsole completes this elegant, feminine design.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-inverted-mahina-monogram-pajama-shirt%20--FPBL20Z58651_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-inverted-mahina-monogram-pajama-shirt%20-ready-to-wear--FPBL20Z58651_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABCJH',
        name: 'Inverted Mahina Monogram Pajama Pants ',
        price: '$1,830.00',
        detail: 'Main Material : 100% Silk',
        intro: 'The Dita sandal contrasts the velvety texture of suede baby goat leather with shiny, gold-tone details: a precious LV Initials chain inspired by the jewelry collection and metallic calfskin on the heel. The upper is distinguished by its slender straps, which are complemented by a flared block heel. A fine leather outsole completes this elegant, feminine design.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-inverted-mahina-monogram-pajama-pants--FPPA28Z58651_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-inverted-mahina-monogram-pajama-pants-ready-to-wear--FPPA28Z58651_PM1_Cropped%20worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46488',
        name: 'Trianon PM',
        price: '$3,050.00',
        detail: '11 x 7.1 x 3.1 inches (length x Height x Width)',
        intro: 'With its more compact format and multiple zipped compartments, this Trianon PM handbag in embossed Monogram Empreinte leather is the perfect alternative to the traditional tote. Its V-cut lines are inspired by the emblematic Louis Vuitton Pallas bag. Two top handles, as well as a detachable shoulder strap, make it comfortable to carry.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm--M46488_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-pm-monogram-empreinte-leather-handbags--M46488_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABHVR',
        name: 'Nina Flat Ballerina',
        price: '$1,170.00',
        detail: 'Printed patent calf leather',
        intro: "The Nina flat ballerina is Louis Vuitton's interpretation of the classic, round-toe ballet pump. This version comes in glossy patent calf leather printed with tiny Monogram Flowers and LV Initials. This feminine, easy-to-wear style is embellished with an LV accessory inspired by the Twist handbag, and finished with a supple leather outsole.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-nina-flat-ballerina--APDP2ATCAL_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-nina-flat-ballerina-shoes--APDP2ATCAL_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABC1N',
        name: 'Golden Button Wool Twill Blazer',
        price: '$3,800.00',
        detail: 'Length : 71 cm / 28 inches',
        intro: "The Nina flat ballerina is Louis Vuitton's interpretation of the classic, round-toe ballet pump. This version comes in glossy patent calf leather printed with tiny Monogram Flowers and LV Initials. This feminine, easy-to-wear style is embellished with an LV accessory inspired by the Twist handbag, and finished with a supple leather outsole.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-golden-button-wool-twill-blazer--FPJA10ZL2002_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-golden-button-wool-twill-blazer-ready-to-wear--FPJA10ZL2002_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABCUI',
        name: 'Open Back Striped Body ',
        price: '$1,570.00',
        detail: 'Main Material : 64% Cotton, 36% Elastane',
        intro: 'A timeless nautical style reimagined with a contemporary feminine silhouette: This long-sleeved body is crafted from comfortable form-fitting stretch jersey in classic horizontal stripes. The elegant bateau neckline is offset with a sensual open back, which can be adjusted with crossover laces. Signed with brass Monogram Flower accents and a graphic LV anchor patch.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-open-back-striped-body%20--FPJT01Z39900_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-open-back-striped-body%20-ready-to-wear--FPJT01Z39900_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82132',
        name: 'LV Charms Card Holder',
        price: '$445.00',
        detail: '4 x 2.9 x 0.1 inches (length x Height x Width)',
        intro: 'The LV Charms card holder comes in soft, grained Monogram Empreinte leather, which is embossed with the Monogram pattern. This essential everyday accessory offers five card slots: two on each side and a larger slot in the middle. It is embellished with two Monogram Flower charms for an irresistibly feminine look.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-charms-card-holder--M82132_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-charms-card-holder-monogram-empreinte-leather-small-leather-goods--M82132_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46487',
        name: 'Trianon MM',
        price: '$3,150.00',
        detail: '14.2 x 8.7 x 3.5 inches (length x Height x Width)',
        intro: 'Made from Monogram Empreinte leather, with its embossed Giant Monogram pattern, the Trianon MM tote is an elegant and functional bag. Two rolled-leather top handles ensure comfortable hand carry while a detachable and adjustable leather strap enable shoulder and cross-body wear. The MM size is roomy enough for daily essentials.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-mm--M46487_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-trianon-mm-monogram-empreinte-leather-handbags--M46487_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABCC6',
        name: 'Inverted Mahina Monogram Chain Shoulder T-Shirt',
        price: '$1,450.00',
        detail: 'Main Material : 100% Cotton',
        intro: 'An elevated spin on a timeless staple: This T-shirt is crafted from soft, breathable cotton jersey in a graphic jacquard of the inverted Mahina Monogram motif. The comfortable, casual shape is refined with an elegant bateau neckline, which is trimmed with brass chain details for a chic nautical touch.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-inverted-mahina-monogram-chain-shoulder-t-shirt%20--FPTS01Z32651_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-inverted-mahina-monogram-chain-shoulder-t-shirt%20-ready-to-wear--FPTS01Z32651_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABH45',
        name: 'Shake Slingback Pump',
        price: '$1,210.00',
        detail: 'Printed patent calf leather',
        intro: "The Shake slingback pump is revisited in patent calf leather with a Monogram print that coordinates with the season's ready-to-wear collection. The glossy leather and bicolor palette complement the modern design of this model, which is notable for its high, V-shaped block heel. The LV accessory on the upper references the clasp of the iconic Twist bag.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-shake-slingback-pump--APVE1ITCAL_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-shake-slingback-pump-shoes--APVE1ITCAL_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82340',
        name: 'Emilie Wallet',
        price: '$830.00',
        detail: '7.5 x 3.9 x 0.8 inches (length x Height x Width)',
        intro: 'Thanks to its slim and elegant design, the Emilie Wallet in grained Monogram Empreinte leather functions both as a wallet and a clutch. Eye-catching, it features an oversized version of the classic Monogram pattern embossed then printed in beige on the black leather. Its roomy interior includes a zipped coin pocket.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-emilie-wallet--M82340_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-emilie-wallet-bicolor-monogram-empreinte-leather-small-leather-goods--M82340_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M22028',
        name: 'Twist MM',
        price: '$5,000.00',
        detail: '9.1 x 6.7 x 3.7 inches (length x Height x Width)',
        intro: 'This Twist MM handbag in Epi grained leather is adorned with a unique triple chain that enables hand-carry, but also shoulder and cross-body wear when two of the thin chains are attached to the leather strap. The triple chain and LV Twist lock feature an iridescent finish that makes them shimmer like a scarab beetle.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-mm--M22028_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-twist-mm-epi-leather-handbags--M22028_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABHF8',
        name: 'Sparkle Slingback Pump',
        price: '$1,350.00',
        detail: '9.5 cm / 3.7-inch heel',
        intro: "The Sparkle slingback pump is a sophisticated style crafted from Epi satin, which evokes the distinctive grain of the House's emblematic Epi leather. It is distinguished by its feminine pointed toe and flared heel with an LV Circle-engraved insert. The elasticized back strap is embellished with an angular, Monogram-engraved chain inspired by the Coussin bag.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-sparkle-slingback-pump--APGE1ISS02_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-sparkle-slingback-pump-shoes--APGE1ISS02_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABGC6',
        name: 'Inverted Mahina Monogram Shirt ',
        price: '$1,830.00',
        detail: 'Main Material : 100% Silk',
        intro: 'A delicate signature elevates this timeless shirt for the season. The fit is slightly relaxed for a casual summery look, which is underscored with soft, fluid silk twill in an allover print of the inverted Mahina Monogram motif. A buttoned collar and patch pocket complete the look with a classic masculine touch.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-inverted-mahina-monogram-shirt%20--FPBL06Z58651_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-inverted-mahina-monogram-shirt%20-ready-to-wear--FPBL06Z58651_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABHQN',
        name: 'Run 55 Sneaker',
        price: '$1,270.00',
        detail: 'Louis Vuitton signature, LV Initials and Monogram Flowers on the back',
        intro: 'This summery version of the Run 55 sneaker combines Monogram denim with lycra, calf leather and metallic lambskin. This sporty model is distinguished by its lifted rubber outsole, which is designed for optimum bounce and comfort. Among its many signature details is a row of Monogram Flowers on the silver-tone spoiler at the back.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-run-55-sneaker--AP4U1ADNBJ_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-run-55-sneaker-shoes--AP4U1ADNBJ_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'LP0335',
        name: 'LV x YK Spell On You',
        price: '$365.00',
        detail: 'Iris from Florence',
        intro: "As part of the major Louis Vuitton x Yayoi Kusama collaboration, the LV x YK Spell on You fragrance is a limited edition inspired by one of the Japanese artist's favorite themes: flowers filled with recurring dots. This hypnotic and feminine motif resonates with the irresistible aura of Spell on You. Created by Master Perfumer Jacques Cavallier Belletrud, this fragrance conjures the alchemy of attraction, an overwhelming passion in a magnetic bouquet around iris pallida blended with sophisticated rose. At once romantic and mischievous, carnal and jubilant, Spell on You captures the excitement of an endless sensuality.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-spell-on-you--LP0335_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-x-yk-spell-on-you-collections--LP0335_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABCR8',
        name: 'Graphic Nautical Knit Cardigan',
        price: '$3,800.00',
        detail: 'Main Material : 41% Viscose, 37% Wool, 18% Polyamide, 2% Elastane, 2% Polyester',
        intro: 'Contemporary details and a graphic motif refresh this classic cardigan for the season. The fit is loose and loungey for relaxed wear, spun from a rich wool-blend knit in a nautical red, white and blue colorway discreetly signed with Monogram accents. Zippers allow the sleeves to be worn open for versatile styling options.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-graphic-nautical-knit-cardigan--FPKC06163610_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-graphic-nautical-knit-cardigan-ready-to-wear--FPKC06163610_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABC7F',
        name: 'Parasol Stripes Jeans',
        price: '$2,350.00',
        detail: 'Main Material : 100% Cotton',
        intro: "These staple boot-cut jeans are playfully reimagined with this season's bright red beach parasol stripes printed on white denim, which is discreetly signed with a tone-on-tone Monogram jacquard and finished with white stitching. The front is fastened with an integrated belt and an exposed zipper trimmed with a two-tone Monogram pull for a contemporary finish.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-parasol-stripes-jeans%20--FPPA10ZT3522_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-parasol-stripes-jeans%20-ready-to-wear--FPPA10ZT3522_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46568',
        name: 'Multi Pochette Accessoires',
        price: '$2,840.00',
        detail: '9.8 x 5.7 x 1.8 inches (length x Height x Width)',
        intro: 'Made from cream-colored Monogram Empreinte leather, the Multi Pochette Accessoires handbag is composed of two pouches attached together. Both pouches are lined with matching cream-color microfiber, with the larger pouch also including an inside pocket. Thanks to a chain and a strap, both removable, this bag becomes very verstaile.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-multi-pochette-accessoires--M46568_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-multi-pochette-accessoires-monogram-empreinte-leather-handbags--M46568_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46676',
        name: 'Neverfull MM',
        price: '$2,710.00',
        detail: '12.2 x 11 x 5.5 inches (length x Height x Width)',
        intro: 'The Neverfull MM tote bag is made from grained Monogram Empreinte leather, with gold-color hardware and a tone-on-tone microfiber lining. A zipped pocket inside can be removed and used separately. The side laces can be tightened for a sleeker look or loosened for more casual use.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-neverfull-mm--M46676_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-neverfull-mm-monogram-empreinte-leather-handbags--M46676_PM1_Side%20view.png?wid=1240&hei=1240',
    },
];

export default products;
