const products = [
    {
        id: 'M81098',
        name: 'Loop',
        price: '$2,370.00',
        detail: '23 x 13 x 6 cm (Length x height x width)',
        intro: 'Created by Nicolas Ghesquière for the Cruise 2022 Collection, the Loop handbag is a half-moon baguette, inspired by the Croissant bag from the House archives. It has a body-friendly, compact shape and a chain for shoulder carry, as well as a cross-body leather strap. The front zip pocket closes with a LV Circle zip pull.',
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-loop--M81098_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-loop-monogram-canvas-handbags--M81098_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M01140',
        name: 'My LV Chain Earrings',
        price: '$585.00',
        detail: 'Height: ~ 1.8 inches/3 cm',
        intro: 'Inspired by the iconic temples of the My LV Chain sunglasses, these earrings offer an elegant new way to wear the Louis Vuitton signature. Chunky brass links are inset with two different House emblems: the LV initials on one and a Monogram Flower on the other. An asymmetrical look that complements the other jewels of the My LV Chain theme.',
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-my-lv-chain-earrings--M01140_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-my-lv-chain-earrings-s00-fashion-jewelry--M01140_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Z1648W',
        name: 'My LV Chain Pilot Sunglasses',
        price: '$705.00',
        detail: 'Gold-color hardware frame',
        intro: "These statement-making My LV Chain Pilot sunglasses bring together a classic silhouette with rich detailing. First created in the Fall-Winter 2021 collection, this season they are offered in a beautifully feminine Pink Gold. They feature chain-link temples that lend the design a jewel-like quality while exhibiting the House's exquisite craftsmanship. LV Initials and Monogram Flowers are elegantly inserted into the links for an additional signature flourish.",
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-my-lv-chain-pilot-sunglasses--Z1648W_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-my-lv-chain-pilot-sunglasses-s00-sunglasses--Z1648W_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M76874',
        name: 'Monogram Classic Shawl',
        price: '$640.00',
        detail: '142.5 x 142.5 cm (Length x height )',
        intro: "This lightweight Monogram Classic shawl is inspired by the blankets of 20th-century travelers. The silk and wool material is dyed in vibrant shades that bring a rich hue to the tone-on-tone Monogram pattern. A fringe finish and jacquard weave construction are a testament to the House's artisanal craftsmanship.",
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-classic-shawl--M76874_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-classic-shawl-s00-shawls-and-stoles--M76874_PM1_Closeup%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1A5M05',
        name: 'Frill Blouse',
        price: '$1,240.00',
        detail: '100% Cotton, Blanc Optique, White',
        intro: 'Tailored from soft cotton poplin embellished with Monogram fil coupé, this Frill Blouse features rich details such as gold LV buttons at the collar and golden Monogram Flower shape embellishments along the front. With feminine frill details at the collar and sleeves, this iconic Louis Vuitton piece is a wardrobe must-have.',
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-frill-blouse--FHBL13AQV000_PM2_Front%20view.png?wid=656&hei=656',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-frill-blouse-ready-to-wear--FHBL13AQV000_PM1_Cropped%20worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M0690U',
        name: 'My LV Chain 25mm Reversible Belt',
        price: '$670.00',
        detail: '90 x 25 cm (Length x width )',
        intro: "This new reversible belt for Spring-Summer 2023 was inspired by Louis Vuitton's iconic My LV Chain sunglasses. In the form of a chain link framing the LV initials, the buckle adds a distinctive signature accent to black calfskin or Monogram canvas. And it pairs perfectly with the My LV Chain bracelet or earrings.",
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-my-lv-chain-25mm-reversible-belt--M0690U_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-my-lv-chain-25mm-reversible-belt-monogram-canvas-belts--M0690U_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AB6R3',
        name: 'Monogram Patch Boot-Cut Jeans ',
        price: '$1,640.00',
        detail: 'Main Material : 100% Cotton',
        intro: 'A signature spin on an enduring staple: These jeans flatter the figure in a high-waisted boot cut that elongates the silhouette, crafted from thick organic denim in a timeless shade for casual everyday styling. A jewel button adds a chic detail, while leather and Monogram patches complete the look with a contemporary House touch.',
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-patch-boot-cut-jeans%20--FOPT11GM1610_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-patch-boot-cut-jeans%20-ready-to-wear--FOPT11GM1610_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AASDF',
        name: 'Run 55 Sneaker',
        price: '$640.00',
        detail: 'Mix of materials',
        intro: 'The Run 55 sneaker comes in a mix of technical materials, which are overlaid on the elaborately constructed upper. Monogram-canvas trim complements this design, which is notable for its numerous signature details, including the LV Circle logo on the tongue. It is finished with a lifted rubber outsole for optimum bounce and comfort.',
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-run-55-sneaker--AO4U1AMI01_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-run-55-sneaker-shoes--AO4U1AMI01_PM1_Cropped%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M81911',
        name: 'Wallet on Chain Ivy',
        price: '$640.00',
        detail: '23.5 x 12 x 4.3 cm (Length x height x width )',
        intro: "Inspired by the Sac Recoleta handbag from the 2000's, the on-trend Wallet On Chain Ivy bag is fashioned from Monogram canvas. The removable gold-color chain allows short-shoulder carry while the adjustable and detachable strap, in natural leather, enables cross-body and long-shoulder carry. Three card slots and a zipped inside pocket make it perfect for everyday essentials.",
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-wallet-on-chain-ivy--M81911_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-wallet-on-chain-ivy-monogram-canvas-wallets-and-small-leather-goods--M81911_PM1_Closeup%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'LP0120',
        name: 'Les Sables Roses',
        price: '$640.00',
        detail: 'Centifolia rose absolute',
        intro: "The desert possesses a singular magic that captivates travelers. At dawn, the sun's first rays blend the dunes and the sky, night and day, and the earth and clouds into a majestic pink. Fascinated by the harmony that springs from contrasts, the Master Perfumer Jacques Cavallier Belletrud has composed a hot and cold perfume playing with two exceptional qualities of rose and oud. Its simple, limpid script underscores the natural beauty and richness of two of perfumery’s most legendary ingredients. The freshness of rose and the woody depths of oud exalt one another, borne aloft by a warm swirl of ambergris.",
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-les-sables-roses--LP0120_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-les-sables-roses-collections--LP0120_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M00609',
        name: 'LV Iconic Earrings',
        price: '$640.00',
        detail: 'Metal with gold-color finish',
        intro: 'These LV Iconic earrings bring to life one of the most recognizable House signatures and give it a modern update. The LV Initials sparkle with a crystal finish across the surface. The stud design makes this pair easy to wear for both casual and more formal occasions.',
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-iconic-earrings--M00609_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-iconic-earrings-s00-fashion-jewelry--M00609_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Z1717U',
        name: 'LV Golden Mask Sunglasses',
        price: '$640.00',
        detail: 'Gold-toned metal frame',
        intro: 'These LV Golden Mask sunglasses are a true testament to Maison craftsmanship. The new design from the Fall-Winter 2022 collection pairs an architectural silhouette with slender temples for an elegant look and lightweight feel. On the front, the 5 Elements signature presents itself through enamel filled studs that perfectly match the color of the lenses.',
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-golden-mask-sunglasses--Z1717U_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-golden-mask-sunglasses-s00-sunglasses--Z1717U_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AB6UX',
        name: 'D-Ring Detail Cashmere Pullover ',
        price: '$640.00',
        detail: 'Main Material : 100% Cashmere',
        intro: 'Understated seasonal detailing refreshes an effortless essential: This pullover has elevated everyday appeal in a soft, lightweight cashmere knit in a warm seasonal shade. The fit is loose and loungey for casual styling, trimmed with comfortable ribbed hems. Two tonal D-ring details add a contemporary touch to the shoulders.',
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-d-ring-detail-cashmere-pullover%20--FOKL19XK6035_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-d-ring-detail-cashmere-pullover%20-ready-to-wear--FOKL19XK6035_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AB6UC',
        name: 'D-Ring Detail Cashmere Jogging Pants ',
        price: '$640.00',
        detail: 'Main Material : 98% Cashmere, 1% Polyamide, 1% Elastane',
        intro: 'These classic jogging pants are revisited in a fine cashmere knit in a warm seasonal shade for an elevated loungewear look. The relaxed fit is finished with ribbed ankles and a drawstring waistband for effortless everyday comfort, while large pockets and D-ring details introduce a discreetly contemporary finishing touch.',
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-d-ring-detail-cashmere-jogging-pants%20--FOKP11XK6035_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-d-ring-detail-cashmere-jogging-pants%20-ready-to-wear--FOKP11XK6035_PM1_Cropped%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1A43L1',
        name: 'LV Archlight Sneaker',
        price: '$640.00',
        detail: 'High and bouncy rubber outsole for extra height (5cm/2 inch)',
        intro: "The statement look of Louis Vuitton's Spring/Summer 2018 fashion show, this futuristic sneaker balances a springy wave-shaped outsole and an oversized tongue with a low cut around the ankle for a delicate, feminine touch.",
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-archlight-sneaker--AE5U6BSL01_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-archlight-sneaker-shoes--AE5U6BSL01_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M45321',
        name: 'OnTheGo MM',
        price: '$640.00',
        detail: '35 x 27 x 14 cm (Length x height x width )',
        intro: "The name says it all: OnTheGo MM takes care of business or shopping, with plenty of room for a busy woman's essentials. With Giant Monogram canvas on one side and Monogram Reverse on the other, it is virtually two bags in one. Twin Toron top handles and two shoulder straps offer several different carry styles, for extra versatility.",
        img1: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-onthego-mm--M45321_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://eu.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-onthego-mm-monogram-canvas-handbags--M45321_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AB9GM',
        name: 'Stripe Accent Monogram Pleated Skirt',
        price: '$3,550.00',
        detail: 'Length : 100 cm / 39,4 inches',
        intro: 'A chic Louis Vuitton twist on a go-to staple: This skirt is crafted in an elegant floor-length silhouette from breezy silk twill that is pleated to emphasize its graceful movement. The Monogram motif adds an iconic allover signature, while the striped waistband introduces a graphic feel. Fastened with an exposed zipper trimmed with an oversized Monogram pull.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-stripe-accent-monogram-pleated-skirt--FOSK45TR0130_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-stripe-accent-monogram-pleated-skirt-ready-to-wear--FOSK45TR0130_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AB37N',
        name: 'Sunny Flat Thong',
        price: '$940.00',
        detail: 'Louis Vuitton-engraved stud',
        intro: "Combining Louis Vuitton's iconic Monogram canvas with calf-leather trim, the Sunny flat thong is both elegant and easy-to-wear. Its V-shaped strap is embellished with tiny, gold-tone studs, inspired by the House's historic trunks, while a larger, engraved stud signs the front. This model is finished with a durable leather outsole.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-sunny-flat-thong--AOXT1ASL33_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-sunny-flat-thong-shoes--AOXT1ASL33_PM1_Side%20view.png?wid=2048&hei=2048',
    },
    {
        id: 'QAB220',
        name: 'Louis Vuitton Horizon Light Up Earphones - Golden',
        price: '$1,660.00',
        detail: 'Sapphire glass top disk with yellow golden back-printing.Yellow golden Connected Monogram pattern. Aluminum frame with yellow golden PVD-coating',
        intro: 'The Louis Vuitton Horizon Light Up earphones mark the beginning of a new era in state-of-the-art exclusive wireless in-ear audio. They bring colour and creativity to the market as well as some of the most innovative, user-focused features around. They come in a beautiful charging case with a silhouette inspired by the Tambour Horizon Light Up watch, whose Monogram pattern animates in ravishing gradient colors. These exclusive earphones will delight fashion-forward individuals and audiophiles alike. Offered in golden-yellow metal, for a jewel-like effect.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-louis-vuitton-horizon-light-up-earphones-golden--QAB220_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-louis-vuitton-horizon-light-up-earphones-golden-tech-objects-and-accessories--QAB220_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46279',
        name: 'Pochette Métis East West',
        price: '$2,910.00',
        detail: '8.5 x 5.3 x 2.4 inches (length x Height x Width)',
        intro: 'Made from Monogram canvas with natural cowhide-leather trim and the S-lock signature, the Pochette Métis East West bag combines emblematic House cues with new contemporary details like a gold-color chain for fashionable short-shoulder carry. Roomy enough to store an iPhone 13, it has three inside compartments, a zipped pocket inside, and another outside.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-m%C3%A9tis-east-west--M46279_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-m%C3%A9tis-east-west-monogram-handbags--M46279_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1ABQLB',
        name: 'LV Isola Flat Mule',
        price: '$780.00',
        detail: 'Metallic lamb leather',
        intro: 'The LV Isola flat mule is crafted from metallic lambskin. This timelessly elegant style is notable for the oversized, cutout LV Circle signature on its strap. This model has a padded insole for added comfort and a durable monobloc outsole constructed from several layers of leather.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-isola-flat-mule--APPH1AMC06_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-isola-flat-mule-shoes--APPH1AMC06_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46569',
        name: 'OnTheGo PM',
        price: '$3,250.00',
        detail: '9.8 x 7.5 x 4.5 inches (length x Height x Width)',
        intro: 'A soft cream-tone makes the Monogram Empreinte leather of this OnTheGo PM bag seem luminous. The LVs and Monogram Flowers embossed into the leather are perfectly complemented by the rectangular lines of this small tote. It can hold smaller essentials like an iPad Mini. Two rolled-leather top handles and a detachable strap give carry options.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-onthego-pm--M46569_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-onthego-pm-monogram-empreinte-leather-handbags--M46569_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M41504',
        name: 'Malle Fleurs',
        price: '$7,450.00',
        detail: '11.6 x 4.5 x 5.7 inches (length x Height x Width)',
        intro: 'A romantic piece rooted in Louis Vuitton history, the Malle Fleurs is a reinterpretation of an iconic piece created in the 1910s for our very best clients: the flower trunk. The water-resistant metallic tray and Vuittonite lining mean that flowers, water, or soil can be put in the tray without damaging it.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-malle-fleurs--M41504_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-malle-fleurs-monogram-canvas-travel--M41504_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M47003',
        name: 'Coffret Tresor 24',
        price: '$5,300.00',
        detail: '9.4 x 4.7 x 6.3 inches (length x Height x Width)',
        intro: 'The medium-size treasure case combines the simplicity of Monogram canvas with the originality of a brightly coloured lining. It securely holds letters, jewellery or other small treasures.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tresor-24--M47003_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-coffret-tresor-24-monogram-canvas-travel--M47003_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M10145',
        name: 'Jewelry Case',
        price: '$1,640.00',
        detail: '7.5 x 3.1 x 3.1 inches (length x Height x Width)',
        intro: 'This refined Etui Bijoux jewelry case is made from Monogram canvas with leather trim. The compact dimensions belie its capacity. Inside, two secure pockets with press-stud closure and two cushions, including one with slots, can hold necklaces, watches, rings, bracelets and earrings. The gold-color S-lock closure provides a refined and feminine touch.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-jewelry-case--M10145_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-jewelry-case-monogram-travel--M10145_PM1_Closeup%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AAZVK',
        name: 'Silhouette Sandal',
        price: '$1,160.00',
        detail: 'Monogram Flower-shaped heel',
        intro: 'The Silhouette sandal is revisited this season in patent Monogram canvas with tonal calf-leather trim. The front strap is embellished with tiny, gold-tone studs inspired by historic Louis Vuitton trunks. The Monogram Flower-shaped heel, which is a key feature of the Silhouette line, is covered in leather for a refined look.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-silhouette-sandal--AOSS1HSL33_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-silhouette-sandal-shoes--AOSS1HSL33_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M46358',
        name: 'Side Trunk',
        price: '$3,800.00',
        detail: '8.3 x 5.5 x 2.4 inches (length x Height x Width)',
        intro: "Returning to the House's trunkmaking beginnings, Nicolas Ghesquière creates the Side Trunk PM handbag in Monogram canvas with leather trim. What strikes the eye is the singularity of the leather zip tab fitted with the iconic S-lock and the reinforced metallic corners. The wide top handle is removable as is the thin leather shoulder strap.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-side-trunk--M46358_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-side-trunk-monogram-handbags--M46358_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M44875',
        name: 'Pochette Métis',
        price: '$2,570.00',
        detail: '9.8 x 7.5 x 2.8 inches (length x Height x Width)',
        intro: "With its on-trend satchel silhouette, the Pochette Métis bag has become an object of fashion desire. This compact, go-everywhere model in the House's Monogram canvas features a distinctive S-lock closure with a polished gold-tone finish. Versatile and unexpectedly roomy, it is fitted with a chic top handle and a long detachable strap for shoulder or cross-body wear.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-m%C3%A9tis--M44875_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-m%C3%A9tis-monogram-handbags--M44875_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M01025',
        name: 'LV Floragram Earrings',
        price: '$530.00',
        detail: 'Metal with gold-color finish',
        intro: 'Each piece in this set of LV Floragram earrings highlights a different Louis Vuitton symbol. The coordinating designs individually showcase a pointed Monogram Flower, a rounded Monogram Flower, and the LV initials. A shared celebration of iconic motifs unites this trio of mismatched earrings for a youthful take on House signatures.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-floragram-earrings--M01025_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-floragram-earrings-s00-fashion-jewelry--M01025_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M00970',
        name: 'LV Floragram Earrings',
        price: '$585.00',
        detail: 'Metal with gold-color finish',
        intro: 'This pair of LV Floragram earrings from the LV Floragram line uses House signatures to enhance a whimsical design. The style showcases LV Initials on the lobe while a trio of pearl-effect resin beads in the shape of a Monogram Flower with a metal center emerges from under the ear. The mix of materials gives these pieces a three-dimensional effect.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-floragram-earrings--M00970_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-floragram-earrings-s00-fashion-jewelry--M00970_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M78656',
        name: 'Monogram Confidential bandeau',
        price: '$220.00',
        detail: '47.2 x 3.1 inches (length x Width)',
        intro: 'A perfect gift, this silk bandeau is printed with emblematic Louis Vuitton details - leather straps, metal chains and padlocks - on a background of the iconic Monogram pattern. This stylish accessory can be worn in many different ways.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-confidential-bandeau--M78656_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-monogram-confidential-bandeau-s00-silk-squares-and-bandeaus--M78656_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M78819',
        name: 'Ultimate Monogram BB Bandeau',
        price: '$210.00',
        detail: '47.2 x 2 inches (length x Width)',
        intro: 'The Ultimate Monogram BB bandeau features chain, strap and padlock motifs that offer an eye-catching interpretation of House signatures. A contrasting Monogram pattern background adds visual dimension to this playful piece. This elegant pure silk accessory will add a luxurious touch to an everyday wardrobe.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-ultimate-monogram-bb-bandeau--M78819_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-ultimate-monogram-bb-bandeau-s00-silk-squares-and-bandeaus--M78819_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M0940A',
        name: 'LV Floragram Bracelet',
        price: '$480.00',
        detail: 'Length: ~7.9 in/20 cm adjustable, ~5.9 in/15 cm',
        intro: "The LV Floragram bracelet features a romantic design. Monogram Flowers hang from the first row of the bracelet, while an LV Initials charm on the second row adds a refined House touch. The pearl-effect resin beads decorating the petals add visual contrast while complementing the piece's delicate sensibility.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-floragram-bracelet--M0940A_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-floragram-bracelet-s00-fashion-jewelry--M0940A_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M00981',
        name: 'LV Floragram Necklace',
        price: '$585.00',
        detail: 'Length: ~17.3 in/44 cm adjustable, ~14.6 in/37 cm',
        intro: "The LV Floragram necklace's double-row style allows two iconic House symbols to shine in one delicate design. The top strand features an LV Initials charm, while a series of Monogram Flowers with pearl-effect resin bead petals decorate the second strand. The combination of different materials creates a three-dimensional effect that highlights the piece's craftsmanship.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-floragram-necklace--M00981_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-floragram-necklace-s00-fashion-jewelry--M00981_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M82336',
        name: 'Clémence Wallet',
        price: '$590.00',
        detail: '7.9 x 3.5 x 0.8 inches (length x Height x Width)',
        intro: 'Monogram Reverse canvas complements the sleek, elegant design of the Clémence wallet. This classic accessory is notable for its secure zip closure and slim-line format. It opens to reveal a leather and canvas lining and a variety of practical pockets and compartments, as well as eight card slots.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cl%C3%A9mence-wallet--M82336_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cl%C3%A9mence-wallet-monogram-reverse-small-leather-goods--M82336_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M43704',
        name: 'Graceful MM',
        price: '$1,890.00',
        detail: '16.1 x 13.8 x 5.5 inches (length x Height x Width)',
        intro: 'The Graceful MM hobo in classic Monogram canvas is an extra-roomy yet lightweight bag to carry every day. Natural cowhide leather detailing and shiny golden hardware add a refined, signature touch. The body-friendly design combines with a supple, flat handle for stylish and comfortable over-the-shoulder wear. The magnetic closure and zipped inside pocket keep belongings secure.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-graceful-mm--M43704_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-graceful-mm-monogram-handbags--M43704_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M44876',
        name: 'Pochette Métis',
        price: '$2,570.00',
        detail: '9.8 x 7.5 x 2.8 inches (length x Height x Width)',
        intro: 'With its distinctive satchel silhouette, the Pochette Métis bag has become an object of fashion desire. This compact, go-everywhere model in trendy Monogram Reverse canvas features a signature S-lock closure with a gleaming gold-tone finish. Versatile and surprisingly roomy, it is fitted with a chic top handle and a long removable strap for shoulder or cross-body wear.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-m%C3%A9tis--M44876_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-pochette-m%C3%A9tis-monogram-reverse-handbags--M44876_PM1_Side%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'GI0859',
        name: 'Notebook Cover Nomade',
        price: '$750.00',
        detail: '14,5 cm x 2cm x 20cm',
        intro: 'The Nomade notebook cover comes in bicolor Monogram Empreinte leather, which is printed and embossed with the iconic Monogram pattern. The cover is secured with an engraved, gold-tone S-lock, inspired by historic Louis Vuitton trunks. Ideal as a gift, this beautifully crafted accessory will be a life-long companion, whether for work or travel.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-notebook-cover-nomade--GI0859_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-notebook-cover-nomade-books-and-stationery--GI0859_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M58907',
        name: 'Neverfull MM',
        price: '$2,850.00',
        detail: '12.2 x 11 x 5.5 inches (length x Height x Width)',
        intro: 'Ideal for everyday use, the roomy Neverfull MM tote bag is made from black cowhide leather with the Monogram pattern embossed then printed in beige on the leather. Cinch the side laces and this tote transforms into an elegant city bag. It can be carried on the shoulder or the elbow, thanks to the long shoulder handles.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-neverfull-mm--M58907_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-neverfull-mm-monogram-empreinte-leather-handbags--M58907_PM1_Back%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1AB73T',
        name: 'Double Face Cashmere Bomber Jacket',
        price: '$4,050.00',
        detail: 'Length : 45 cm / 17,7 inches',
        intro: 'This bomber jacket is crafted from elegant double face cashmere for an elevated everyday look. The sporty silhouette is reimagined with feminine proportions, while an understated stitched circle detail on the chest discreetly recalls a classic varsity patch. Complete with chic golden hardware and iconic Monogram accents. A sophisticated staple.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-double-face-cashmere-bomber-jacket%20--FOJA11QRA653_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-double-face-cashmere-bomber-jacket%20-ready-to-wear--FOJA11QRA653_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: '1A4PFE',
        name: 'Side Strap T-Shirt',
        price: '$915.00',
        detail: '100% Cotton',
        intro: 'This side strap T-shirt is a wardrobe basic with a fashion-forward twist. Crafted from soft jersey, it is embellished with gold Monogram flower hardware around the neckline. Meanwhile, the waist can be adjusted using fabric side straps inspired by kimono obi belts and a signature metallic D-ring.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-side-strap-t-shirt--FGTS03JG2900_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-side-strap-t-shirt-ready-to-wear--FGTS03JG2900_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Z1986W',
        name: 'LV Malletage Cat Eye Sunglasses',
        price: '$925.00',
        detail: 'Hand-assembled LV-engraved Malletage studs on the temples',
        intro: "The sophisticated look of the new LV Malletage Cat Eye Sunglasses recalls the diamond pattern of the padding lining Louis Vuitton's historic trunks. The golden metal Malletage studs on the hand-assembled temples come engraved with the LV Initials for a refined signature touch. With their classic feminine shape, these sunglasses are flattering to the face and easy on the eyes.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-malletage-cat-eye-sunglasses--Z1986W_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-malletage-cat-eye-sunglasses-s00-sunglasses--Z1986W_PM2_Front%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'M78448',
        name: 'Up And Away Square 90',
        price: '$485.00',
        detail: '35.4 x 35.4 inches (length x Height)',
        intro: "This new square scarf joins the 'Up and Away' theme inspired by the House's travel heritage. Pure silk is screen-printed with a richly detailed image of hot air balloons, many adorned with the Monogram pattern, carrying Louis Vuitton trunks, bags and suitcases. A panorama of House icons, it makes a great gift.",
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-up-and-away-square-90--M78448_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-up-and-away-square-90-s00-silk-squares-and-bandeaus--M78448_PM1_Interior%20view.png?wid=1240&hei=1240',
    },
    {
        id: 'Z1626U',
        name: 'LV Jewel Cat Eye Sunglasses',
        price: '$800.00',
        detail: 'LV Initials on chain-effect temples',
        intro: 'Delicate rimless lenses combine with bold chain-effect temples to give the LV Jewel Cat Eye sunglasses their unique look. Classic House signatures are revealed in subtle details throughout this pair. The iconic LV Initials are incorporated into the chain link design while hand-polished Monogram Flower studs adorn the smoky gradient lenses.',
        img1: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-jewel-cat-eye-sunglasses--Z1626U_PM2_Front%20view.png?wid=456&hei=456',
        img2: 'https://us.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-lv-jewel-cat-eye-sunglasses-s00-sunglasses--Z1626U_PM1_Worn%20view.png?wid=1240&hei=1240',
    },
];

export default products;
